# Generated by Django 6.0.4 on 2026-06-27 14:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0045_alter_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyChainItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Item ID')),
                ('uom', models.CharField(default='Sheets', max_length=20, verbose_name='UOM')),
                ('sheet_packing_pcs', models.IntegerField(default=1, verbose_name='Sheet Packing/Pcs')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Unit Cost')),
                ('safety_stock', models.IntegerField(default=0, verbose_name='Safety Stock')),
                ('max_stock_level', models.IntegerField(default=10000, verbose_name='Maximum Stock Level')),
                ('lead_time_days', models.IntegerField(default=1, verbose_name='Lead Time (Days)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supply_chain_details', to='core.material')),
            ],
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('OPENING', 'Opening'), ('RECEIVING', 'Receiving'), ('ISSUANCE', 'Issuance'), ('ADJUSTMENT', 'Adjustment')], max_length=20)),
                ('month_str', models.CharField(blank=True, max_length=20, null=True, verbose_name='Month')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('gin_jc', models.CharField(blank=True, max_length=50, null=True, verbose_name='GIN / JC')),
                ('sheet_qty_pcs', models.IntegerField(default=0, verbose_name='Sheet Qty/Pcs')),
                ('pkt_rim_qty', models.IntegerField(default=0, verbose_name='Pkt/Rim Qty')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='supply_chain.supplychainitem')),
            ],
        ),
        migrations.CreateModel(
            name='StockDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_str', models.CharField(blank=True, max_length=20, null=True, verbose_name='Month')),
                ('sheet_qty_pcs', models.IntegerField(default=0, verbose_name='Sheet Qty/Pcs')),
                ('pkt_rim_qty', models.IntegerField(default=0, verbose_name='Pkt/Rim Qty')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demands', to='supply_chain.supplychainitem')),
            ],
        ),
    ]
