# Generated by Django 6.0.4 on 2026-06-28 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_userprofile_role'),
        ('supply_chain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='job_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transactions', to='core.jobcard'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='production',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_issuance', to='core.production'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('JOB_CARD', 'Job Card')], default='MANUAL', max_length=20),
        ),
    ]
