# Generated by Django 6.0.4 on 2026-06-28 06:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0002_stocktransaction_job_card_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalStockCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_date', models.DateField(default=django.utils.timezone.now, verbose_name='Count Date')),
                ('physical_sheet_qty', models.IntegerField(default=0, verbose_name='Physical Sheet Qty/Pcs')),
                ('physical_pkt_rim_qty', models.IntegerField(default=0, verbose_name='Physical Pkt/Rim Qty')),
                ('system_sheet_qty', models.IntegerField(default=0, verbose_name='System Sheet Qty/Pcs')),
                ('system_pkt_rim_qty', models.IntegerField(default=0, verbose_name='System Pkt/Rim Qty')),
                ('accuracy_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Inventory Accuracy %')),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_counts', to='supply_chain.supplychainitem')),
            ],
            options={
                'ordering': ['-count_date', '-id'],
            },
        ),
    ]
