# Generated by Django 6.0.4 on 2026-07-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0005_physicalstockcount_is_active_stockdemand_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Is Approved'),
        ),
    ]
