# Generated by Django 6.0.4 on 2026-07-19 17:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_seed_application_types'),
        ('supply_chain', '0006_stocktransaction_is_approved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRequestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(help_text='Short prefix used in the IR-ID, e.g. RM, CON, MNT, SPR', max_length=4)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Item Request Type',
                'verbose_name_plural': 'Item Request Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ItemRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_no', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='IR-ID')),
                ('request_date', models.DateField(default=django.utils.timezone.now)),
                ('item_title', models.CharField(max_length=255, verbose_name='Item Title')),
                ('machine_other', models.CharField(blank=True, default='', max_length=150, verbose_name='Machine (if not in list)')),
                ('uom', models.CharField(max_length=30, verbose_name='Unit of Measure')),
                ('specifications', models.TextField(verbose_name='Specifications / Technical Details')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description / Purpose of Use')),
                ('dimensions', models.CharField(blank=True, default='', max_length=100, verbose_name='Dimensions (if applicable)')),
                ('local_import', models.CharField(blank=True, choices=[('LOCAL', 'Local'), ('IMPORT', 'Import')], default='', max_length=10)),
                ('part_number', models.CharField(blank=True, default='', max_length=100, verbose_name='Part Number')),
                ('required_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Required Quantity')),
                ('estimated_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='item_requests/%Y/%m/')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('MGR_REVIEW', 'Manager Review'), ('SC_REVIEW', 'Supply Chain Review'), ('APPROVED', 'Approved'), ('IN_PROCUREMENT', 'In Procurement'), ('RECEIVED', 'Received'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected'), ('NEEDS_AMENDMENT', 'Needs Amendment'), ('NEEDS_INFO', 'Needs More Info')], db_index=True, default='SUBMITTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_requests', to='core.department')),
                ('existing_sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_requests', to='supply_chain.rawmaterialsku')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_requests', to='core.machine')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_requests', to=settings.AUTH_USER_MODEL)),
                ('request_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='supply_chain.itemrequesttype')),
            ],
            options={
                'verbose_name': 'Item Request',
                'verbose_name_plural': 'Item Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemProcurementTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(blank=True, default='', max_length=50)),
                ('code_opened_date', models.DateField(blank=True, null=True)),
                ('indent_pr_no', models.CharField(blank=True, default='', max_length=50)),
                ('pr_date', models.DateField(blank=True, null=True)),
                ('po_no', models.CharField(blank=True, default='', max_length=50)),
                ('po_date', models.DateField(blank=True, null=True)),
                ('supplier', models.CharField(blank=True, default='', max_length=150)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('received_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_procurement_updates', to=settings.AUTH_USER_MODEL)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='procurement', to='supply_chain.itemrequest')),
            ],
            options={
                'verbose_name': 'Item Procurement Timeline',
                'verbose_name_plural': 'Item Procurement Timelines',
            },
        ),
        migrations.CreateModel(
            name='ItemRequestApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SUBMIT', 'Submit'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('AMEND', 'Needs Amendment'), ('MORE_INFO', 'Needs More Info'), ('RESUBMIT', 'Resubmit')], max_length=20)),
                ('stage', models.CharField(choices=[('REQUESTER', 'Requester'), ('MANAGER', 'Manager'), ('SUPPLY_CHAIN', 'Supply Chain')], max_length=20)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_request_approvals', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='supply_chain.itemrequest')),
            ],
            options={
                'verbose_name': 'Item Request Approval',
                'verbose_name_plural': 'Item Request Approvals',
                'ordering': ['created_at'],
            },
        ),
    ]
