# Generated by Django 6.0.4 on 2026-07-19 18:09

import django.db.models.deletion
from django.db import migrations, models


SEED_DEPARTMENTS = ['Offset Production', 'Flexo Production', 'Sublimation Production']


def seed_departments_and_clear_stale_requests(apps, schema_editor):
    """Seed the dedicated Item Request departments.

    Existing ItemRequest rows (dev/test data created before this dedicated
    department lookup existed) pointed at core.Department ids, which don't
    exist in the new table, so they're cleared here rather than migrated.
    """
    ItemRequestDepartment = apps.get_model('supply_chain', 'ItemRequestDepartment')
    for name in SEED_DEPARTMENTS:
        ItemRequestDepartment.objects.get_or_create(name=name, defaults={'is_active': True})

    ItemRequest = apps.get_model('supply_chain', 'ItemRequest')
    ItemRequest.objects.all().delete()


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0008_seed_item_request_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRequestDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Item Request Department',
                'verbose_name_plural': 'Item Request Departments',
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(seed_departments_and_clear_stale_requests, noop_reverse),
        migrations.AlterField(
            model_name='itemrequest',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('MGR_REVIEW', 'Manager Review'), ('SC_REVIEW', 'Supply Chain Review'), ('APPROVED', 'Approved'), ('IN_PROCUREMENT', 'In Procurement'), ('RECEIVED', 'Received'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected'), ('NEEDS_REVISION', 'Needs Revision')], db_index=True, default='SUBMITTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='itemrequestapproval',
            name='action',
            field=models.CharField(choices=[('SUBMIT', 'Submit'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('REVISE', 'Needs Revision'), ('RESUBMIT', 'Resubmit')], max_length=20),
        ),
        migrations.AlterField(
            model_name='itemrequesttype',
            name='code',
            field=models.CharField(help_text='Short prefix used in the IR-ID, e.g. RM, CON, MNT', max_length=4),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_requests', to='supply_chain.itemrequestdepartment'),
        ),
    ]
