# Generated by Django 6.0.4 on 2026-07-19 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0010_merge_maintenance_and_spare_part_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrequest',
            name='cost_centre',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Budget / Cost Centre'),
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_requests_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='model_name',
            field=models.CharField(choices=[('RawMaterialSku', 'Raw Material SKU'), ('StockDemand', 'Monthly Demand'), ('StockTransaction', 'Stock Transaction'), ('PhysicalStockCount', 'Physical Stock Count'), ('ItemRequest', 'Item Request')], max_length=50),
        ),
        migrations.AlterField(
            model_name='itemrequestapproval',
            name='action',
            field=models.CharField(choices=[('SUBMIT', 'Submit'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('REVISE', 'Needs Revision'), ('RESUBMIT', 'Resubmit'), ('EDIT', 'Edited (post-approval)'), ('EDIT_REQUESTED', 'Edit Requested (pending change review)'), ('DELETE', 'Deleted')], max_length=20),
        ),
    ]
