# Generated by Django 6.0.4 on 2026-07-19 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0011_itemrequest_cost_centre_itemrequest_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRequestQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=150)),
                ('quoted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('file', models.FileField(upload_to='item_requests/quotes/%Y/%m/')),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('procurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='supply_chain.itemprocurementtimeline')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_request_quotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item Request Quote',
                'verbose_name_plural': 'Item Request Quotes',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
