# Generated by Django 5.2.16 on 2026-07-21 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0012_itemrequestquote'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemprocurementtimeline',
            name='sku',
            field=models.ForeignKey(blank=True, help_text='Link to an existing SKU. Leave blank while a new code is being opened.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_timelines', to='supply_chain.rawmaterialsku', verbose_name='Linked SKU'),
        ),
        migrations.AddField(
            model_name='itemprocurementtimeline',
            name='sku_pre_existing',
            field=models.BooleanField(default=False, help_text='True when the request was linked to an existing SKU, so code opening was not required.', verbose_name='SKU already existed'),
        ),
        migrations.AddField(
            model_name='rawmaterialsku',
            name='sku_type',
            field=models.ForeignKey(blank=True, help_text='Raw Material, Consumable, Service, Maintenance, …', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='raw_material_skus', to='supply_chain.itemrequesttype', verbose_name='SKU Type'),
        ),
    ]
