# Generated by Django 6.0.4 on 2026-04-13 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_card_no', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=100)),
                ('order_qty', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_date', models.DateField()),
                ('dispatch_qty', models.IntegerField()),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jobcard')),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift', models.CharField(max_length=20)),
                ('machine', models.CharField(max_length=50)),
                ('output_qty', models.IntegerField()),
                ('waste_qty', models.IntegerField(default=0)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jobcard')),
            ],
        ),
    ]
