# Generated by Django 6.0.4 on 2026-04-14 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('standard_speed', models.FloatField(default=4000)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_card_no', models.CharField(max_length=50)),
                ('month', models.CharField(blank=True, max_length=20, null=True)),
                ('po_date', models.DateField(blank=True, null=True)),
                ('PO_No', models.CharField(blank=True, max_length=50, null=True)),
                ('SKU', models.CharField(max_length=100)),
                ('colour', models.IntegerField(blank=True, null=True)),
                ('application', models.CharField(blank=True, max_length=100, null=True)),
                ('order_qty', models.IntegerField()),
                ('ups', models.IntegerField(blank=True, null=True)),
                ('print_sheet_size', models.CharField(blank=True, max_length=50, null=True)),
                ('wastage', models.IntegerField(default=0)),
                ('actual_sheet_required', models.IntegerField(blank=True, null=True)),
                ('purchase_sheet_size', models.CharField(blank=True, max_length=50, null=True)),
                ('purchase_sheet_ups', models.IntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('destination', models.CharField(blank=True, max_length=100, null=True)),
                ('die_cutting', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Open', max_length=20)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department')),
                ('machine_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.machine')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.material')),
            ],
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_date', models.DateField()),
                ('dispatch_qty', models.IntegerField(default=0)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jobcard')),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('A', 'Shift A'), ('B', 'Shift B'), ('C', 'Shift C')], max_length=10)),
                ('output_qty', models.PositiveIntegerField()),
                ('waste_qty', models.PositiveIntegerField(default=0)),
                ('planned_time', models.FloatField()),
                ('run_time', models.FloatField()),
                ('downtime', models.FloatField(default=0)),
                ('setup_time', models.FloatField(default=0)),
                ('ideal_run_rate', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='core.jobcard')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.machine')),
                ('operator', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Production Team'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
