# Generated by Django 6.0.4 on 2026-04-13 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobcard',
            old_name='customer_name',
            new_name='SKU',
        ),
    ]
