# Generated by Django 6.0.4 on 2026-04-14 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_operator_alter_production_shift_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='operator',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.operator'),
        ),
    ]
