# Generated by Django 6.0.4 on 2026-04-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_customer_name_jobcard_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='PO_No',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
