# Generated by Django 6.0.4 on 2026-04-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_production_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='dc_no',
            field=models.CharField(blank=True, help_text='Dispatch Challan Number', max_length=50, null=True, unique=True),
        ),
    ]
