# Generated by Django 6.0.4 on 2026-04-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_jobcard_po_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='status',
            field=models.CharField(default='Open', max_length=20),
        ),
    ]
