# Generated by Django 6.0.4 on 2026-04-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_jobcard_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='Material',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
