# Generated by Django 6.0.4 on 2026-04-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dispatch_dc_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='production',
            old_name='output_qty',
            new_name='output_sheets',
        ),
        migrations.RenameField(
            model_name='production',
            old_name='waste_qty',
            new_name='waste_sheets',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='actual_sheet_required',
        ),
        migrations.AlterField(
            model_name='production',
            name='downtime',
            field=models.FloatField(default=0, help_text='in minutes'),
        ),
        migrations.AlterField(
            model_name='production',
            name='planned_time',
            field=models.FloatField(help_text='in minutes'),
        ),
        migrations.AlterField(
            model_name='production',
            name='run_time',
            field=models.FloatField(help_text='in minutes'),
        ),
        migrations.AlterField(
            model_name='production',
            name='setup_time',
            field=models.FloatField(default=0, help_text='in minutes'),
        ),
    ]
