# Generated by Django 6.0.4 on 2026-04-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_jobcard_material'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobcard',
            old_name='Material',
            new_name='colour',
        ),
        migrations.AddField(
            model_name='jobcard',
            name='actual_sheet_required',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='application',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='destination',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='die_cutting',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='machine_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='material',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='month',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='po_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='print_sheet_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='purchase_sheet_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='purchase_sheet_ups',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='ups',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='wastage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='job_card_no',
            field=models.CharField(max_length=50, verbose_name='JC'),
        ),
    ]
