# Generated by Django 6.0.4 on 2026-04-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_output_qty_production_output_sheets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='dc_no',
            field=models.CharField(blank=True, error_messages={'unique': 'This DC number already exists!'}, help_text='Dispatch Challan Number', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='job_card_no',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='wastage',
            field=models.IntegerField(default=0, help_text='in Sheets'),
        ),
        migrations.AlterField(
            model_name='production',
            name='shift',
            field=models.CharField(choices=[('A', 'Shift A'), ('B', 'Shift B')], max_length=1),
        ),
    ]
