# Generated by Django 6.0.4 on 2026-04-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_dispatch_dc_no_alter_jobcard_job_card_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='standard_speed',
        ),
        migrations.AddField(
            model_name='machine',
            name='standard_impressions_per_hour',
            field=models.FloatField(default=4000, help_text='Standard printing speed in impressions per hour'),
        ),
        migrations.AddField(
            model_name='production',
            name='impressions',
            field=models.PositiveIntegerField(default=0, help_text='Total impressions produced (sheets × passes)'),
            preserve_default=False,
        ),
    ]
