# Generated by Django 6.0.4 on 2026-04-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_machine_standard_speed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='dc_no',
            field=models.CharField(blank=True, error_messages={'unique': 'This DC number already exists!'}, help_text='Dispatch Challan Number (can be shared across multiple Job Cards)', max_length=50, null=True),
        ),
    ]
