# Generated by Django 6.0.4 on 2026-04-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_jobcard_colour_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='dispatch_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='PO_No',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='output_qty',
            field=models.IntegerField(default=0),
        ),
    ]
