# Generated by Django 6.0.4 on 2026-04-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_dispatch_dc_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='dc_no',
            field=models.CharField(blank=True, help_text='Dispatch Challan Number (can be shared across multiple Job Cards)', max_length=50, null=True),
        ),
    ]
