# Generated by Django 6.0.4 on 2026-04-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_dispatch_dc_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='downtime_category',
            field=models.CharField(blank=True, choices=[('setup', 'Setup Time (Planned - Excluded from OEE)'), ('maintenance', 'Maintenance (Planned - Excluded from OEE)'), ('breakdown', 'Machine Breakdown (Unplanned - Affects OEE)'), ('material', 'Material Issue (External - Excluded from OEE)'), ('operator', 'Operator Issue (Affects OEE)'), ('other', 'Other (Affects OEE)')], help_text='Category of downtime', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='waste_reason',
            field=models.CharField(blank=True, choices=[('paper_jam', 'Paper Jam (Affects OEE Quality)'), ('color_issue', 'Color/Registration Issue (Affects OEE Quality)'), ('material_defect', 'Material Defect (External - Excluded from OEE)'), ('operator_error', 'Operator Error (Affects OEE Quality)'), ('machine_issue', 'Machine Issue (Affects OEE Quality)'), ('other', 'Other (Affects OEE Quality)')], help_text='Primary reason for waste', max_length=20, null=True),
        ),
    ]
