# Generated by Django 6.0.4 on 2026-04-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_production_downtime_category_production_waste_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='total_impressions_required',
            field=models.IntegerField(blank=True, help_text='Total impressions required for this job (manually entered based on machine config - 1/2/5 color, front-back, etc.)', null=True),
        ),
    ]
