# Generated by Django 6.0.4 on 2026-04-16 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_jobcard_total_impressions_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin — Full system access'), ('pm', 'Production Manager — Job cards, production oversight'), ('operator', 'Machine Operator — Production entry only'), ('storekeeper', 'Store Keeper — Material & inventory management'), ('qc', 'QC Inspector — Quality checks'), ('dispatch', 'Dispatch Team — Dispatch entry & management'), ('finance', 'Finance Viewer — Read-only analytics & reports')], default='operator', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
