# Generated by Django 6.0.4 on 2026-04-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin — Full system access & configuration'), ('manager', 'Manager — Overall oversight (jobs, production, dispatch, reports)'), ('planner', 'Planner — Create & manage job cards, view analytics'), ('production', 'Production Supervisor — Manage production entries & team'), ('operator', 'Machine Operator — Production entry only'), ('dispatch', 'Dispatch Coordinator — Dispatch approval & tracking'), ('qc', 'QC Inspector — Quality checks & approvals'), ('storekeeper', 'Store Keeper — Material & inventory management'), ('finance', 'Finance Viewer — Read-only analytics & reports')], default='operator', max_length=20),
        ),
    ]
