# Generated by Django 6.0.4 on 2026-04-16 00:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_userprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('job_card', 'Job Card'), ('production', 'Production'), ('dispatch', 'Dispatch')], max_length=20)),
                ('record_id', models.PositiveIntegerField()),
                ('record_label', models.CharField(max_length=200)),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated')], max_length=20)),
                ('change_reason', models.TextField(blank=True)),
                ('field_changes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, related_name='change_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='changelog',
            index=models.Index(fields=['entity_type', 'record_id'], name='core_change_entity__61b92a_idx'),
        ),
        migrations.AddIndex(
            model_name='changelog',
            index=models.Index(fields=['created_at'], name='core_change_created_55dfd3_idx'),
        ),
    ]