# Generated by Django 6.0.4 on 2026-04-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_changelog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='changelog',
            new_name='core_change_entity__4f0d80_idx',
            old_name='core_change_entity__61b92a_idx',
        ),
        migrations.RenameIndex(
            model_name='changelog',
            new_name='core_change_created_1da5d6_idx',
            old_name='core_change_created_55dfd3_idx',
        ),
        migrations.AddField(
            model_name='dispatch',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='production',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='action',
            field=models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted')], max_length=20),
        ),
    ]
