# Generated by Django 6.0.4 on 2026-04-17 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_editoverriderequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='colour',
            field=models.CharField(blank=True, help_text='Supports values like 4, 1+1, 2+0', max_length=20, null=True),
        ),
    ]
