# Generated by Django 6.0.4 on 2026-04-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_jobcard_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='is_print_job',
            field=models.BooleanField(default=True, help_text='Uncheck for Cut & Pack jobs (no printing, dispatch directly against order qty)'),
        ),
    ]
