# Generated by Django 6.0.4 on 2026-04-17 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_created_by_to_jobcard_production_dispatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('shift', models.CharField(choices=[('A', 'Shift A'), ('B', 'Shift B')], max_length=1)),
                ('net_hours', models.FloatField(default=11.0, help_text='Net available production hours after breaks (e.g. 11 for 12hr shift - 60min break)')),
            ],
            options={
                'ordering': ['day_of_week', 'shift'],
                'unique_together': {('day_of_week', 'shift')},
            },
        ),
        migrations.CreateModel(
            name='MachineWorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('shift', models.CharField(choices=[('A', 'Shift A'), ('B', 'Shift B')], max_length=1)),
                ('is_working', models.BooleanField(default=False, help_text='Uncheck = machine is OFF on this day+shift (e.g. GTO off Friday, on Sunday)')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedule', to='core.machine')),
            ],
            options={
                'ordering': ['machine', 'day_of_week', 'shift'],
                'unique_together': {('machine', 'day_of_week', 'shift')},
            },
        ),
    ]
