# Generated by Django 6.0.4 on 2026-04-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_shift_config_machine_schedule_overrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='estimated_run_time_minutes',
            field=models.FloatField(blank=True, help_text='Auto-estimated run time in minutes from impressions and machine speed', null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='estimated_setup_time_minutes',
            field=models.FloatField(blank=True, help_text='Auto-estimated setup time in minutes from colors and machine setup rate', null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='estimated_total_time_minutes',
            field=models.FloatField(blank=True, help_text='Auto-estimated total planned time in minutes (run + setup)', null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='standard_setup_minutes_per_color',
            field=models.FloatField(default=15, help_text='Default setup/make-ready minutes per color for planning'),
        ),
    ]
