# Generated by Django 6.0.4 on 2026-04-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_jobcard_estimated_run_time_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='production_tolerance_percent',
            field=models.FloatField(default=5, help_text='Allowed extra production over planned sheets in percent'),
        ),
    ]
