# Generated by Django 6.0.4 on 2026-04-17 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_jobcard_production_tolerance_percent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='short_close_close_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='short_close_closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='short_close_closed_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobcards_short_closed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='short_close_closed_qty',
            field=models.PositiveIntegerField(default=0, help_text='Quantity manager has explicitly short-closed from pending completion gap'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='short_close_wastage_qty',
            field=models.PositiveIntegerField(default=0, help_text='Short-close quantity moved to wastage bucket by manager decision'),
        ),
    ]
