# Generated by Django 6.0.4 on 2026-04-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_jobcard_short_close_close_reason_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='machineworkschedule',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='shiftconfig',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='machineworkschedule',
            name='effective_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machineworkschedule',
            name='effective_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shiftconfig',
            name='effective_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shiftconfig',
            name='effective_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='machineworkschedule',
            unique_together={('machine', 'day_of_week', 'shift', 'effective_from', 'effective_to')},
        ),
        migrations.AlterUniqueTogether(
            name='shiftconfig',
            unique_together={('day_of_week', 'shift', 'effective_from', 'effective_to')},
        ),
    ]
