# Generated by Django 6.0.4 on 2026-04-18 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_machineworkschedule_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionDowntime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('setup', 'Setup Time (Planned - Excluded from OEE)'), ('maintenance', 'Maintenance (Planned - Excluded from OEE)'), ('breakdown', 'Machine Breakdown (Unplanned - Affects OEE)'), ('material', 'Material Issue (External - Excluded from OEE)'), ('operator', 'Operator Issue (Affects OEE)'), ('other', 'Other (Affects OEE)')], max_length=20)),
                ('minutes', models.FloatField(help_text='Downtime minutes for this category')),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downtime_entries', to='core.production')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
