# Generated by Django 6.0.4 on 2026-04-28 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_userprofile_role'),
        ('planning', '0015_alter_planningjob_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='planning_job',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_card', to='planning.planningjob'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='total_sheet_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='action',
            field=models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('restore', 'Restored'), ('submit', 'Submitted'), ('approve', 'Approved'), ('reject', 'Rejected'), ('release', 'Released'), ('start_production', 'Start Production'), ('complete', 'Completed'), ('close', 'Closed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('pending_data', 'Pending Data'), ('planning_approved', 'Planning Approved'), ('pending_qc', 'Pending QC'), ('qc_approved', 'QC Approved'), ('qc_rejected', 'QC Rejected'), ('pending_pm_approval', 'Pending Production Manager Approval'), ('production_approved', 'Production Approved'), ('pm_rejected', 'PM Rejected'), ('released', 'Released'), ('in_production', 'In Production'), ('completed', 'Completed'), ('closed', 'Closed')], default='pending_data', max_length=40),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin — Full system access & configuration'), ('manager', 'Manager — Overall oversight (jobs, production, dispatch, reports)'), ('planner', 'Planner — Create & manage job cards, view analytics'), ('production_manager', 'Production Manager — Final approval and release'), ('production', 'Production Supervisor — Manage production entries & team'), ('operator', 'Machine Operator — Production entry only'), ('dispatch', 'Dispatch Coordinator — Dispatch approval & tracking'), ('qc', 'QC Inspector — Quality checks & approvals'), ('storekeeper', 'Store Keeper — Material & inventory management'), ('finance', 'Finance Viewer — Read-only analytics & reports')], default='operator', max_length=20),
        ),
    ]
