# Generated by Django 6.0.4 on 2026-04-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_jobcard_planning_job_jobcard_total_sheet_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
