# Generated by Django 6.0.4 on 2026-04-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_jobcard_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='total_colors',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
