# Generated by Django 6.0.4 on 2026-06-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_approve_sku_master',
            field=models.BooleanField(default=False, help_text='Allow this user to approve/reject SKUs in master review'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_sku_master_review',
            field=models.BooleanField(default=False, help_text='Allow this user to view and manage SKU master review queue'),
        ),
    ]
