# Generated by Django 6.0.4 on 2026-06-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_add_sku_master_review_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='action',
            field=models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('restore', 'Restored'), ('submit', 'Submitted'), ('approve', 'Approved'), ('reject', 'Rejected'), ('release', 'Released'), ('start_production', 'Start Production'), ('complete', 'Completed'), ('close', 'Closed'), ('send_plate', 'Sent to Vendor'), ('receive_plate', 'Received from Vendor'), ('mark_available', 'Available for Production'), ('archive', 'Archived')], max_length=20),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='entity_type',
            field=models.CharField(choices=[('job_card', 'Job Card'), ('production', 'Production'), ('dispatch', 'Dispatch'), ('plate_request', 'Plate Request')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin — Full system access & configuration'), ('manager', 'Manager — Overall oversight (jobs, production, dispatch, reports)'), ('planner', 'Planner — Create & manage job cards, view analytics'), ('production_manager', 'Production Manager — Final approval and release'), ('production', 'Production Supervisor — Manage production entries & team'), ('graphics_designer', 'Graphics Designer — Manage plate request workflow'), ('operator', 'Machine Operator — Production entry only'), ('dispatch', 'Dispatch Coordinator — Dispatch approval & tracking'), ('qc', 'QC Inspector — Quality checks & approvals'), ('storekeeper', 'Store Keeper — Material & inventory management'), ('finance', 'Finance Viewer — Read-only analytics & reports')], default='operator', max_length=20),
        ),
    ]
