# Generated by Django 6.0.4 on 2026-06-11 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_changelog_action_alter_changelog_entity_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionWipStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_wip_statuses_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Production WIP Status',
                'verbose_name_plural': 'Production WIP Statuses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobCardWipStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='production_wip_status', to='core.jobcard')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_card_wip_status_updates', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_card_wip_statuses', to='core.productionwipstatus')),
            ],
            options={
                'verbose_name': 'Job Card WIP Status',
                'verbose_name_plural': 'Job Card WIP Statuses',
            },
        ),
    ]
