# Generated by Django 6.0.4 on 2026-06-17 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_jobcard_purchase_sheet_ups_alter_jobcard_ups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='change_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='counter_end',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='production',
            name='counter_start',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='production',
            name='downtime_category_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='remark_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('hold', 'Hold'), ('cancelled', 'Cancelled')], default='in_progress', max_length=20),
        ),
        migrations.AddField(
            model_name='production',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productions_supervised', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='production',
            name='waste_reason_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
