# Generated by Django 6.0.4 on 2026-06-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_add_make_ready_and_downtime_minutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='downtime',
        ),
        migrations.RemoveField(
            model_name='production',
            name='setup_time',
        ),
        migrations.AlterField(
            model_name='production',
            name='downtime_category',
            field=models.CharField(blank=True, choices=[('maintenance', 'Maintenance (Planned - Excluded from OEE)'), ('breakdown', 'Machine Breakdown (Unplanned - Affects OEE)'), ('material', 'Material Issue (External - Excluded from OEE)'), ('operator', 'Operator Issue (Affects OEE)'), ('other', 'Other (Affects OEE)')], help_text='Category of downtime', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='productiondowntime',
            name='category',
            field=models.CharField(choices=[('maintenance', 'Maintenance (Planned - Excluded from OEE)'), ('breakdown', 'Machine Breakdown (Unplanned - Affects OEE)'), ('material', 'Material Issue (External - Excluded from OEE)'), ('operator', 'Operator Issue (Affects OEE)'), ('other', 'Other (Affects OEE)')], max_length=20),
        ),
    ]
