# Generated by Django 6.0.4 on 2026-06-18 10:14

import django.db.models.deletion
from django.db import migrations, models


def migrate_supervisors(apps, schema_editor):
    Production = apps.get_model('core', 'Production')
    Supervisor = apps.get_model('core', 'Supervisor')
    User = apps.get_model('auth', 'User')
    db_alias = schema_editor.connection.alias

    supervisor_ids = Production.objects.using(db_alias).filter(supervisor_id__isnull=False).values_list('supervisor_id', flat=True).distinct()
    for supervisor_id in supervisor_ids:
        if not supervisor_id:
            continue
        existing = Supervisor.objects.using(db_alias).filter(pk=supervisor_id).first()
        if existing:
            continue
        user = User.objects.using(db_alias).filter(pk=supervisor_id).first()
        if user:
            name = f"{(user.first_name or '').strip()} {(user.last_name or '').strip()}".strip() or user.username
        else:
            name = f"Imported Supervisor {supervisor_id}"
        Supervisor.objects.using(db_alias).create(id=supervisor_id, name=name)


def reverse_migrate_supervisors(apps, schema_editor):
    # no reverse data migration required; keep created supervisors if rollback happens.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_remove_production_downtime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('employee_code', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RunPython(migrate_supervisors, reverse_migrate_supervisors),
        migrations.AlterField(
            model_name='production',
            name='supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.supervisor'),
        ),
    ]
