# Generated by Django 6.0.4 on 2026-07-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='purchase_sheet_ups',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='ups',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
