# Generated by Django 6.0.4 on 2026-07-03 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_notification'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='core_notifi_user_id_f286cd_idx',
            old_name='core_notifi_user_id_7f0b0a_idx',
        ),
    ]
