# Generated by Django 6.0.4 on 2026-07-05 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_default_notifications(apps, schema_editor):
    NotificationEvent = apps.get_model('core', 'NotificationEvent')
    NotificationRule = apps.get_model('core', 'NotificationRule')
    WorkflowTransition = apps.get_model('core', 'WorkflowTransition')

    # Seed events
    events_data = [
        {
            'code': 'sku.pending_review',
            'name': 'SKU Sent for QC',
            'description': 'Fired when a planner submits a SKU recipe for QC review.',
            'module': 'SKU',
            'title_template': 'SKU ready for review: {% if instance.sku %}{{ instance.sku }}{% else %}{{ instance }}{% endif %}',
            'message_template': '{% if instance.job_name %}{{ instance.job_name }}{% else %}Submitted for QC review.{% endif %}',
            'link_template': '/planning/sku/{% if instance.pk %}{{ instance.pk }}{% endif %}/edit/',
        },
        {
            'code': 'sku.sent_back',
            'name': 'SKU Sent Back / Rejected',
            'description': 'Fired when QC returns a SKU recipe to draft with comments.',
            'module': 'SKU',
            'title_template': 'SKU sent back: {% if instance.sku %}{{ instance.sku }}{% else %}{{ instance }}{% endif %}',
            'message_template': '{% if instance.rejection_comment %}{{ instance.rejection_comment }}{% else %}Returned to draft for correction.{% endif %}',
            'link_template': '/planning/sku/{% if instance.pk %}{{ instance.pk }}{% endif %}/edit/',
        },
        {
            'code': 'plate.replacement_requested',
            'name': 'Plate Replacement Requested',
            'description': 'Fired when a new plate set remake is requested for a Job Card.',
            'module': 'Plate',
            'title_template': 'Plate replacement: {% if instance.jc_number %}{{ instance.jc_number }}{% else %}job{% endif %}',
            'message_template': '{% if instance.damaged_colors %}{{ instance.damaged_colors }}{% elif instance.remarks %}{{ instance.remarks }}{% else %}Replacement plates requested.{% endif %}',
            'link_template': '/printing_plates/requests/{% if instance.pk %}{{ instance.pk }}{% endif %}/',
        },
        {
            'code': 'plate.cancelled',
            'name': 'Plate Request Cancelled',
            'description': 'Fired when an open plate request is cancelled.',
            'module': 'Plate',
            'title_template': 'Plate request cancelled: {% if instance.jc_number %}{{ instance.jc_number }}{% else %}job{% endif %}',
            'message_template': '{% if instance.progress %}{{ instance.progress }}{% elif instance.remarks %}{{ instance.remarks }}{% else %}Plates marked not required.{% endif %}',
            'link_template': '/printing_plates/requests/{% if instance.pk %}{{ instance.pk }}{% endif %}/',
        },
    ]

    events_map = {}
    for data in events_data:
        event, _ = NotificationEvent.objects.update_or_create(
            code=data['code'],
            defaults=data
        )
        events_map[data['code']] = event

    # Seed rules
    rules_data = [
        ('sku.pending_review', 'role', 'qc'),
        ('sku.pending_review', 'role', 'admin'),
        ('sku.pending_review', 'role', 'manager'),

        ('sku.sent_back', 'role', 'planner'),
        ('sku.sent_back', 'role', 'graphics_designer'),
        ('sku.sent_back', 'role', 'admin'),
        ('sku.sent_back', 'role', 'manager'),
        ('sku.sent_back', 'creator', None),

        ('plate.replacement_requested', 'role', 'graphics_designer'),
        ('plate.replacement_requested', 'role', 'admin'),
        ('plate.replacement_requested', 'role', 'manager'),

        ('plate.cancelled', 'role', 'planner'),
        ('plate.cancelled', 'role', 'admin'),
        ('plate.cancelled', 'role', 'manager'),
    ]

    for event_code, recipient_type, target in rules_data:
        event = events_map.get(event_code)
        if not event:
            continue
        
        defaults = {
            'enabled': True,
            'recipient_type': recipient_type,
            'exclude_actor': True,
            'in_app_enabled': True,
        }
        if recipient_type == 'role':
            defaults['role'] = target
        elif recipient_type == 'creator':
            defaults['send_to_creator'] = True
            
        NotificationRule.objects.get_or_create(
            event=event,
            recipient_type=recipient_type,
            role=target if recipient_type == 'role' else None,
            defaults=defaults
        )

    # Seed workflow transitions
    transitions_data = [
        ('SKU', 'draft', 'Submit', 'pending_review', 'qc'),
        ('SKU', 'pending_review', 'Approve', 'reviewed', 'admin'),
        ('SKU', 'reviewed', 'Approve', 'approved', 'graphics_designer'),
        ('Plate', 'draft', 'Send', 'sent_to_vendor', 'graphics_designer'),
        ('Plate', 'sent_to_vendor', 'Receive', 'received_from_vendor', 'graphics_designer'),
        ('Plate', 'received_from_vendor', 'Available', 'available_for_production', 'production'),
    ]

    for module, current_stage, action, next_stage, notify_role in transitions_data:
        WorkflowTransition.objects.update_or_create(
            module=module,
            current_stage=current_stage,
            action=action,
            next_stage=next_stage,
            defaults={'notify_role': notify_role}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_rename_core_notifi_user_id_7f0b0a_idx_core_notifi_user_id_f286cd_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=80, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('module', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('title_template', models.CharField(blank=True, max_length=200)),
                ('message_template', models.TextField(blank=True)),
                ('link_template', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='core.department'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates_as_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates_as_supervisor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('recipient_type', models.CharField(choices=[('role', 'Role'), ('user', 'Specific User'), ('department', 'Department'), ('creator', 'Creator'), ('manager', 'Manager'), ('supervisor', 'Supervisor'), ('next_stage', 'Next Workflow Stage')], default='role', max_length=50)),
                ('role', models.CharField(blank=True, choices=[('admin', 'Admin — Full system access & configuration'), ('manager', 'Manager — Overall oversight (jobs, production, dispatch, reports)'), ('planner', 'Planner — Create & manage job cards, view analytics'), ('production_manager', 'Production Manager — Final approval and release'), ('production', 'Production Supervisor — Manage production entries & team'), ('graphics_designer', 'Graphics Designer — Manage plate request workflow'), ('operator', 'Machine Operator — Production entry only'), ('dispatch', 'Dispatch Coordinator — Dispatch approval & tracking'), ('qc', 'QC Inspector — Quality checks & approvals'), ('storekeeper', 'Store Keeper — Material & inventory management'), ('finance', 'Finance Viewer — Read-only analytics & reports'), ('supply_chain', 'Supply Chain — Manage supply chain dashboard & stock')], max_length=50, null=True)),
                ('send_to_creator', models.BooleanField(default=False)),
                ('send_to_manager', models.BooleanField(default=False)),
                ('send_to_supervisor', models.BooleanField(default=False)),
                ('send_to_next_stage', models.BooleanField(default=False)),
                ('exclude_actor', models.BooleanField(default=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('email_enabled', models.BooleanField(default=False)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_rules', to='core.department')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='core.notificationevent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_rules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationRuleAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_rule_audits', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.notificationrule')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=100)),
                ('current_stage', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=100)),
                ('next_stage', models.CharField(max_length=100)),
                ('notify_role', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'unique_together': {('module', 'current_stage', 'action', 'next_stage')},
            },
        ),
        migrations.RunPython(seed_default_notifications),
    ]
