# Generated by Django 6.0.4 on 2026-07-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_fix_dispatch_notification_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='dispatch_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('pending_data', 'Pending Data'), ('planning_approved', 'Planning Approved'), ('pending_qc', 'Pending QC'), ('qc_approved', 'QC Approved'), ('qc_rejected', 'QC Rejected'), ('pending_pm_approval', 'Pending Production Manager Approval'), ('production_approved', 'Production Approved'), ('pm_rejected', 'PM Rejected'), ('released', 'Released'), ('in_production', 'In Production'), ('completed', 'Completed'), ('closed', 'Closed')], db_index=True, default='pending_data', max_length=40),
        ),
        migrations.AlterField(
            model_name='production',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
