# Generated by Django 6.0.4 on 2026-07-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_auto_sync_and_backfill_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcardwipstatus',
            name='is_manual',
            field=models.BooleanField(default=False, help_text='Set to True if manually overridden by a user'),
        ),
    ]
