# Generated by Django 6.0.4 on 2026-07-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_jobcardwipstatus_is_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='default_colors',
            field=models.PositiveSmallIntegerField(default=1, help_text='Nominal colour capacity of the machine (e.g. 1 or 2)'),
        ),
        migrations.AddField(
            model_name='machine',
            name='machine_group_code',
            field=models.CharField(blank=True, help_text='Stable code used to group machines by colour class, e.g. GTO1, GTO2, SM74', max_length=20),
        ),
        migrations.AddField(
            model_name='machine',
            name='max_print_length_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='max_print_width_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='min_print_length_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='min_print_width_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='operational_colors',
            field=models.PositiveSmallIntegerField(default=1, help_text='Currently working colour units. 0 = under maintenance; lower than default_colors = temporarily degraded'),
        ),
    ]
