# Generated by Django 6.0.4 on 2026-07-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_machine_fleet_color_size_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='machine_type',
            field=models.CharField(blank=True, choices=[('offset_printing', 'Offset Printing'), ('digital_printing', 'Digital Printing'), ('cutting', 'Cutting'), ('other', 'Other')], default='other', help_text="What kind of machine this is. Colour/size fields below only apply to Offset Printing machines - fill them in only where they're relevant.", max_length=30),
        ),
        migrations.AlterField(
            model_name='machine',
            name='default_colors',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Nominal colour capacity of the machine (e.g. 1 or 2). Offset printing machines only.', null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='operational_colors',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Currently working colour units. 0 = under maintenance; lower than default_colors = temporarily degraded. Offset printing machines only.', null=True),
        ),
    ]
