# Generated by Django 5.2.16 on 2026-07-21 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_alter_notificationrule_role_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='merge_allocated_ups',
            field=models.PositiveIntegerField(blank=True, help_text="This SKU's ups on the combined merge sheet; overrides job-card ups for piece counting.", null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='merge_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merge_children', to='core.production'),
        ),
    ]
