# Generated by Django 5.2.16 on 2026-07-23 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_production_merge_allocated_ups_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='pass_count_override',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Supervisor override for the number of print passes on this job (e.g. 2→4 when a machine colour unit is under maintenance). Leave blank to use the planned pass count.', null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='pass_count_override_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='pass_count_override_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pass_overrides_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='pass_count_override_reason',
            field=models.CharField(blank=True, help_text='Why the pass count was overridden (required when an override is set).', max_length=255, null=True),
        ),
    ]
