# Generated by Django 5.2.16 on 2026-07-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_jobcard_pass_count_override_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='editoverriderequest',
            name='consumed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
