# Generated by Django 5.2.16 on 2026-08-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_emailsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='dc_no',
            field=models.CharField(db_index=True, help_text='Dispatch Challan / DR number (required; can be shared across multiple Job Cards and SKUs)', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='PO_No',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='SKU',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
