# Generated by Django 5.2.16 on 2026-08-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_add_dispatch_jobcard_perf_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nav_layout',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
