# Generated by Django 5.2.16 on 2026-08-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_userprofile_nav_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationrule',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin — Full system access & configuration'), ('manager', 'Manager — Overall oversight (jobs, production, dispatch, reports)'), ('planner', 'Planner — Create & manage job cards, view analytics'), ('production_manager', 'Production Manager — Final approval and release'), ('production', 'Production Supervisor — Manage production entries & team'), ('graphics_designer', 'Graphics Designer — Manage plate request workflow'), ('operator', 'Machine Operator — Production entry only'), ('dispatch', 'Dispatch Coordinator — Dispatch approval & tracking'), ('qc', 'QC Inspector — Quality checks & approvals'), ('storekeeper', 'Store Keeper — Material & inventory management'), ('finance', 'Finance Viewer — Read-only analytics & reports'), ('supply_chain', 'Supply Chain — Manage supply chain dashboard & stock'), ('maintenance_engineer', 'Maintenance Engineer — Log faults, raise spares/service demand, track downtime'), ('viewer', 'Viewer — Read-only access to every page, full chat access')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin — Full system access & configuration'), ('manager', 'Manager — Overall oversight (jobs, production, dispatch, reports)'), ('planner', 'Planner — Create & manage job cards, view analytics'), ('production_manager', 'Production Manager — Final approval and release'), ('production', 'Production Supervisor — Manage production entries & team'), ('graphics_designer', 'Graphics Designer — Manage plate request workflow'), ('operator', 'Machine Operator — Production entry only'), ('dispatch', 'Dispatch Coordinator — Dispatch approval & tracking'), ('qc', 'QC Inspector — Quality checks & approvals'), ('storekeeper', 'Store Keeper — Material & inventory management'), ('finance', 'Finance Viewer — Read-only analytics & reports'), ('supply_chain', 'Supply Chain — Manage supply chain dashboard & stock'), ('maintenance_engineer', 'Maintenance Engineer — Log faults, raise spares/service demand, track downtime'), ('viewer', 'Viewer — Read-only access to every page, full chat access')], default='operator', max_length=20),
        ),
    ]
