# Generated by Django 5.2.16 on 2026-08-15 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_dispatchchangerequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_enabled', models.BooleanField(default=True, help_text='Master switch for every AI feature. Turning this off disables AI everywhere immediately — bot summaries, chat assistant — no restart needed.')),
                ('bot_summaries_enabled', models.BooleanField(default=True, help_text="Allow bot report emails to include an AI-written summary paragraph, for bots that also have their own 'Use AI Summary' option turned on.")),
                ('chat_assistant_enabled', models.BooleanField(default=True, help_text='Allow the AI Assistant chat bot to reply to messages at all. Turning this off makes it stop responding entirely, rather than replying with unphrased raw data.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Settings',
                'verbose_name_plural': 'AI Settings',
            },
        ),
    ]
