# Generated by Django 5.2.16 on 2026-08-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_aisettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintPassOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Number of press passes, e.g. 1, 2, 3, 4', max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Print Pass Option',
                'verbose_name_plural': 'Print Pass Options',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
