# Generated by Django 5.2.16 on 2026-08-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_seed_print_pass_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='official_email',
            field=models.EmailField(blank=True, help_text="Company/official email for automated notifications (task assignments, reminders, etc.). Falls back to the account's login email if left blank — set this when a user's login email is personal rather than official.", max_length=254),
        ),
    ]
