# Generated by Django 5.2.16 on 2026-08-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_userprofile_official_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
