# Generated by Django 5.2.16 on 2026-09-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_jobcard_form_label_jobcard_parent_job_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='pcs_per_unit',
            field=models.PositiveIntegerField(default=1, help_text='Pieces per order unit — 500 for a rim, pages-per-book for a book SKU, etc. Used only for internal press-sheet/ups planning; 1 for standard pcs jobs.'),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='unit_type',
            field=models.CharField(choices=[('pcs', 'Pieces'), ('rim', 'Rims'), ('book', 'Books'), ('box', 'Boxes')], default='pcs', max_length=10),
        ),
    ]
