# Generated by Django 5.2.16 on 2026-09-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_alter_jobcard_pcs_per_unit_alter_jobcard_unit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='default_pcs_per_unit',
            field=models.PositiveIntegerField(blank=True, help_text="Pieces per order unit for this product type, when it's fixed across the category (e.g. 500 for 'A4 Rim' — every rim is 500 sheets). Leave blank when it varies per SKU (e.g. 'Report Books' — page count differs per document) so each SKU's master record sets its own.", null=True),
        ),
        migrations.AddField(
            model_name='producttype',
            name='default_unit_type',
            field=models.CharField(choices=[('pcs', 'Pieces'), ('rim', 'Rims'), ('book', 'Books'), ('box', 'Boxes')], default='pcs', help_text="Order-qty unit every SKU of this product type uses, regardless of what the WO/PO's own unit column happens to say (that text is unreliable — 'PIECE' is used for plain pcs, rims, and books alike). E.g. 'A4 Rim' product type -> rim, so any SKU classified under it is a rim job without a planner having to set that per SKU.", max_length=10),
        ),
    ]
