# Generated by Django 6.0.4 on 2026-09-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_seed_product_type_unit_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machine_type',
            field=models.CharField(blank=True, choices=[('offset_printing', 'Offset Printing'), ('digital_printing', 'Digital Printing'), ('flexo_printing', 'Flexo Printing'), ('cutting', 'Cutting'), ('other', 'Other')], default='other', help_text="What kind of machine this is. Colour/size fields below only apply to Offset Printing machines - fill them in only where they're relevant.", max_length=30),
        ),
    ]
