# Generated by Django 6.0.4 on 2026-10-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_seed_print_pass_option_5'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='last_error_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='last_error_message',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='last_success_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
