# Generated by Django 6.0.4 on 2026-06-05 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0037_alter_changelog_action_alter_changelog_entity_type_and_more'),
        ('planning', '0020_planningjob_change_request_pending_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft_request', 'Draft Request'), ('sent_to_vendor', 'Sent to Vendor'), ('received_from_vendor', 'Received from Vendor'), ('available_for_production', 'Available for Production'), ('archived', 'Archived')], default='draft_request', max_length=40)),
                ('set_no', models.CharField(blank=True, max_length=120)),
                ('new_set_no', models.CharField(blank=True, max_length=120)),
                ('plate_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('plate_color', models.CharField(blank=True, max_length=120)),
                ('vendor', models.CharField(blank=True, max_length=120)),
                ('remarks', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('challan', models.CharField(blank=True, max_length=120)),
                ('chalan_sign', models.BooleanField(default=False)),
                ('box', models.CharField(blank=True, max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to='printing_plates/images/')),
                ('link', models.URLField(blank=True)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.department')),
                ('designer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plate_requests_designed', to=settings.AUTH_USER_MODEL)),
                ('job_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plate_requests', to='core.jobcard')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.machine')),
                ('planning_job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plate_requests', to='planning.planningjob')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plate_requests_received', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plate_requests_requested', to=settings.AUTH_USER_MODEL)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plate_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('sku_recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plate_requests', to='planning.skurecipe')),
            ],
            options={
                'verbose_name': 'Plate Request',
                'verbose_name_plural': 'Plate Requests',
                'ordering': ['-requested_at', '-created_at'],
            },
        ),
    ]
