# Generated by Django 6.0.4 on 2026-06-05 10:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_changelog_action_alter_changelog_entity_type_and_more'),
        ('planning', '0020_planningjob_change_request_pending_and_more'),
        ('printing_plates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='platerequest',
            index=models.Index(fields=['planning_job'], name='printing_pl_plannin_66a0f0_idx'),
        ),
        migrations.AddIndex(
            model_name='platerequest',
            index=models.Index(fields=['status'], name='printing_pl_status_a24310_idx'),
        ),
        migrations.AddIndex(
            model_name='platerequest',
            index=models.Index(fields=['requested_at'], name='printing_pl_request_de51c5_idx'),
        ),
    ]
