# Generated by Django 6.0.4 on 2026-06-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing_plates', '0002_platerequest_printing_pl_plannin_66a0f0_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platerequest',
            name='impression',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='platerequest',
            name='progress',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='platerequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent_to_vendor', 'Sent to Vendor'), ('received_from_vendor', 'Received from Vendor'), ('available_for_production', 'Available for Production'), ('archived', 'Archived')], default='draft', max_length=40),
        ),
        migrations.RunPython(
            lambda apps, schema_editor: apps.get_model('printing_plates', 'PlateRequest').objects.filter(status='draft_request').update(status='draft'),
            reverse_code=migrations.RunPython.noop,
        ),
    ]
