# Generated by Django 6.0.4 on 2026-06-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing_plates', '0003_platerequest_impression_platerequest_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platerequest',
            name='awc_no',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
