# Generated by Django 6.0.4 on 2026-06-29 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0026_alter_planningjob_planning_stage'),
        ('printing_plates', '0004_platerequest_awc_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platerequest',
            name='planning_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plate_requests', to='planning.planningjob'),
        ),
    ]
