# Generated by Django 6.0.4 on 2026-07-03 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printing_plates', '0006_platerequest_replacement_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='platerequest',
            new_name='printing_pl_source_f00284_idx',
            old_name='printing_pl_source_idx',
        ),
    ]
