# Generated by Django 5.2.16 on 2026-07-21 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing_plates', '0009_platerequest_die_cutting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='platerequest',
            name='retained_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platerequest',
            name='retained_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plate_requests_retained', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='platerequest',
            name='retained_for_reuse',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='platerequest',
            name='retained_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='platerequest',
            name='retained_released_at',
            field=models.DateTimeField(blank=True, help_text='Set when a later job for this SKU picked the retained plate set back up.', null=True),
        ),
    ]
