# Generated by Django 5.2.16 on 2026-08-17 14:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SheetsSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('tab_name', models.CharField(blank=True, max_length=100)),
                ('batch_size', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sheets Sync Log',
                'verbose_name_plural': 'Sheets Sync Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SheetsSyncSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Turn on to start mirroring data to the configured Google Spreadsheet.')),
                ('spreadsheet_id', models.CharField(blank=True, help_text="The ID from the spreadsheet's URL (…/spreadsheets/d/<this>/edit).", max_length=100)),
                ('service_account_json_path', models.CharField(blank=True, help_text='Path to the service-account credentials JSON file. Leave blank to use the GOOGLE_SERVICE_ACCOUNT_JSON / GOOGLE_APPLICATION_CREDENTIALS env vars or the default gspread credentials location.', max_length=255)),
                ('flush_interval_seconds', models.PositiveIntegerField(default=4, help_text='How often (seconds) queued changes are pushed to Sheets.')),
                ('max_batch_size', models.PositiveIntegerField(default=500, help_text='Maximum queued changes drained per flush cycle.')),
                ('circuit_breaker_failure_threshold', models.PositiveIntegerField(default=5, help_text='Consecutive failed flushes before pausing sync temporarily.')),
                ('circuit_breaker_cooldown_seconds', models.PositiveIntegerField(default=300, help_text='How long sync stays paused after the circuit breaker opens.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sheets Sync Setting',
                'verbose_name_plural': 'Sheets Sync Settings',
            },
        ),
        migrations.CreateModel(
            name='SheetsRowIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_name', models.CharField(db_index=True, max_length=100)),
                ('object_pk', models.CharField(max_length=64)),
                ('row_number', models.PositiveIntegerField(help_text='1-based data row (header excluded).')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sheets Row Index',
                'verbose_name_plural': 'Sheets Row Indexes',
                'indexes': [models.Index(fields=['tab_name', 'object_pk'], name='sheets_sync_tab_nam_1e0cee_idx')],
                'unique_together': {('tab_name', 'object_pk')},
            },
        ),
    ]
