# Generated by Django 5.2.16 on 2026-07-31 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroom_avatar_chatroom_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('doc', 'Document'), ('other', 'Other')], default='other', max_length=10),
        ),
    ]
