from .models import JobCard, Production, Dispatch

AUDIT_CONFIG = {
    'job_card': {
        'model': JobCard,
        'permission': 'can_edit_jobcard',
        'list_view': 'job_card_records',
        'fields': [
            'job_card_no', 'SKU', 'PO_No', 'po_date', 'month', 'material', 'colour', 'application',
            'order_qty', 'total_impressions_required', 'ups', 'wastage', 'print_sheet_size',
            'purchase_sheet_size', 'purchase_sheet_ups', 'machine_name', 'department', 'destination',
            'die_cutting', 'status', 'remarks',
        ],
        'labels': {
            'job_card_no': 'Job Card No',
            'SKU': 'SKU',
            'PO_No': 'PO Number',
            'po_date': 'PO Date',
            'month': 'Month',
            'material': 'Material',
            'colour': 'Colours',
            'application': 'Application',
            'order_qty': 'Order Qty',
            'total_impressions_required': 'Total Impressions Required',
            'ups': 'UPS',
            'wastage': 'Wastage',
            'print_sheet_size': 'Print Sheet Size',
            'purchase_sheet_size': 'Purchase Sheet Size',
            'purchase_sheet_ups': 'Purchase Sheet UPS',
            'machine_name': 'Machine',
            'department': 'Department',
            'destination': 'Destination',
            'die_cutting': 'Die Cutting',
            'status': 'Status',
            'remarks': 'Remarks',
        },
    },
    'production': {
        'model': Production,
        'permission': 'can_edit_production',
        'list_view': 'production_records',
        'fields': [
            'job_card', 'machine', 'operator', 'shift', 'date', 'impressions', 'output_sheets',
            'waste_sheets', 'planned_time', 'run_time', 'setup_time', 'downtime', 'downtime_category',
            'downtime_breakdown_text',
            'waste_reason',
        ],
        'labels': {
            'job_card': 'Job Card',
            'machine': 'Machine',
            'operator': 'Operator',
            'shift': 'Shift',
            'date': 'Production Date',
            'impressions': 'Impressions',
            'output_sheets': 'Output Sheets',
            'waste_sheets': 'Waste Sheets',
            'planned_time': 'Planned Time',
            'run_time': 'Run Time',
            'setup_time': 'Setup Time',
            'downtime': 'Downtime',
            'downtime_category': 'Downtime Category',
            'downtime_breakdown_text': 'Downtime Breakdown',
            'waste_reason': 'Waste Reason',
        },
    },
    'dispatch': {
        'model': Dispatch,
        'permission': 'can_approve_dispatch',
        'list_view': 'dispatch_records',
        'fields': ['job_card', 'dc_no', 'dispatch_date', 'dispatch_qty'],
        'labels': {
            'job_card': 'Job Card',
            'dc_no': 'DC No',
            'dispatch_date': 'Dispatch Date',
            'dispatch_qty': 'Dispatch Qty',
        },
    },
}
