# Generated by Django 6.0.4 on 2026-04-18 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jc_number', models.CharField(max_length=50, unique=True)),
                ('plan_month', models.CharField(blank=True, max_length=20)),
                ('plan_date', models.DateField(blank=True, null=True)),
                ('po_number', models.CharField(blank=True, max_length=120)),
                ('sku', models.CharField(blank=True, max_length=255)),
                ('job_name', models.CharField(blank=True, max_length=255)),
                ('repeat_flag', models.CharField(blank=True, max_length=50)),
                ('material', models.CharField(blank=True, max_length=120)),
                ('color_spec', models.CharField(blank=True, max_length=60)),
                ('application', models.CharField(blank=True, max_length=120)),
                ('size_w_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('size_h_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('size_w_inch', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('size_h_inch', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('print_pcs', models.PositiveIntegerField(blank=True, null=True)),
                ('ups', models.PositiveIntegerField(blank=True, null=True)),
                ('print_sheet_size', models.CharField(blank=True, max_length=80)),
                ('print_sheets', models.PositiveIntegerField(blank=True, null=True)),
                ('wastage_sheets', models.PositiveIntegerField(blank=True, null=True)),
                ('actual_sheet_required', models.PositiveIntegerField(blank=True, null=True)),
                ('purchase_sheet_size', models.CharField(blank=True, max_length=80)),
                ('purchase_sheet_ups', models.PositiveIntegerField(blank=True, null=True)),
                ('purchase_sheet_required', models.PositiveIntegerField(blank=True, null=True)),
                ('pkt_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('requirement', models.TextField(blank=True)),
                ('front_colors', models.PositiveIntegerField(blank=True, null=True)),
                ('back_colors', models.PositiveIntegerField(blank=True, null=True)),
                ('total_colors', models.PositiveIntegerField(blank=True, null=True)),
                ('total_mr_time_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('front_pass', models.PositiveIntegerField(blank=True, null=True)),
                ('back_pass', models.PositiveIntegerField(blank=True, null=True)),
                ('planned_total_impressions', models.PositiveIntegerField(blank=True, null=True)),
                ('mi_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('mi_balance', models.PositiveIntegerField(blank=True, null=True)),
                ('remaining_sheet', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=40)),
                ('pr_reference', models.CharField(blank=True, max_length=120)),
                ('rejected_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('balance_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('destination', models.CharField(blank=True, max_length=120)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('stock_bag', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('machine_name', models.CharField(blank=True, max_length=120)),
                ('purchase_material', models.CharField(blank=True, max_length=120)),
                ('stock_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('daily_demand', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('plate_set_no', models.CharField(blank=True, max_length=120)),
                ('awc_no', models.CharField(blank=True, max_length=120)),
                ('aging_days', models.PositiveIntegerField(blank=True, null=True)),
                ('die_cutting', models.CharField(blank=True, max_length=120)),
                ('issued_to_production', models.BooleanField(default=False)),
                ('job_card_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_jobs_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-plan_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PoDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_file', models.FileField(upload_to='planning/po_docs/')),
                ('extracted_payload', models.JSONField(blank=True, null=True)),
                ('extraction_status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('planning_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_documents', to='planning.planningjob')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_po_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanningDispatchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_index', models.PositiveSmallIntegerField()),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('dc_no', models.CharField(blank=True, max_length=80)),
                ('delivered_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('planning_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_runs', to='planning.planningjob')),
            ],
            options={
                'ordering': ['dispatch_index'],
                'unique_together': {('planning_job', 'dispatch_index')},
            },
        ),
        migrations.CreateModel(
            name='PlanningPrintRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_index', models.PositiveSmallIntegerField()),
                ('print_date', models.DateField(blank=True, null=True)),
                ('print_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('wastage_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('planning_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_runs', to='planning.planningjob')),
            ],
            options={
                'ordering': ['run_index'],
                'unique_together': {('planning_job', 'run_index')},
            },
        ),
    ]
