# Generated by Django 6.0.4 on 2026-04-18 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkuRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=255, unique=True)),
                ('job_name', models.CharField(blank=True, max_length=255)),
                ('material', models.CharField(blank=True, max_length=120)),
                ('color_spec', models.CharField(blank=True, max_length=60)),
                ('application', models.CharField(blank=True, max_length=120)),
                ('size_w_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('size_h_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ups', models.PositiveIntegerField(blank=True, null=True)),
                ('print_sheet_size', models.CharField(blank=True, max_length=80)),
                ('purchase_sheet_size', models.CharField(blank=True, max_length=80)),
                ('purchase_material', models.CharField(blank=True, max_length=120)),
                ('machine_name', models.CharField(blank=True, max_length=120)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('default_unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sku_recipes_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sku'],
            },
        ),
    ]
