# Generated by Django 6.0.4 on 2026-04-18 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_skurecipe_approved_at_skurecipe_approved_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='planningjob',
            name='edited_fields_list',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='planningjob',
            name='has_edits_since_creation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planningjob',
            name='last_edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planningjob',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_jobs_edited', to=settings.AUTH_USER_MODEL),
        ),
    ]
