# Generated by Django 6.0.4 on 2026-04-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_planningjob_edited_fields_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skurecipe',
            name='awc_no',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='skurecipe',
            name='daily_demand',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='skurecipe',
            name='die_cutting',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='skurecipe',
            name='plate_set_no',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='skurecipe',
            name='purchase_sheet_ups',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
