# Generated by Django 6.0.4 on 2026-04-19 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_skurecipe_awc_no_skurecipe_daily_demand_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='skurecipe',
            name='last_rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skurecipe',
            name='last_rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sku_recipes_rejected', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skurecipe',
            name='rejection_comment',
            field=models.TextField(blank=True),
        ),
    ]
