# Generated by Django 6.0.4 on 2026-04-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0006_add_rejection_comment_to_skurecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='skurecipe',
            name='lamination_front_and_back',
            field=models.BooleanField(default=False, help_text='Lamination is applied on both front and back'),
        ),
    ]
