# Generated by Django 6.0.4 on 2026-04-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0007_skurecipe_lamination_front_and_back'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skurecipe',
            name='master_data_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('reviewed', 'Reviewed'), ('approved', 'Approved')], default='draft', max_length=20),
        ),
    ]
