# Generated by GitHub Copilot

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0008_alter_skurecipe_master_data_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='skurecipe',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='skurecipe',
            name='archive_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='skurecipe',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name='sku_recipes_archived',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='skurecipe',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
