# Generated by Django 6.0.4 on 2026-04-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0009_add_skurecipe_archiving'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skurecipe',
            name='master_data_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('reviewed', 'Pending Approval (Manager)'), ('approved', 'Approved')], default='draft', max_length=20),
        ),
    ]
