# Generated by Django 6.0.4 on 2026-04-22 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0010_alter_skurecipe_master_data_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='planningjob',
            name='archive_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='planningjob',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planningjob',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_jobs_archived', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planningjob',
            name='hold_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planningjob',
            name='hold_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_jobs_held', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planningjob',
            name='hold_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='planningjob',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='planningjob',
            name='is_on_hold',
            field=models.BooleanField(default=False),
        ),
    ]
