# Generated by Django 6.0.4 on 2026-04-22 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0011_planningjob_archive_reason_planningjob_archived_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='planningjob',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planningjob',
            name='restored_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_jobs_restored', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planningjob',
            name='restore_reason',
            field=models.TextField(blank=True),
        ),
    ]
