# Generated by Django 6.0.4 on 2026-04-23 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0012_add_planningjob_restore_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skurecipe',
            name='department',
        ),
    ]
