# Generated by Django 6.0.4 on 2026-04-28 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0013_remove_skurecipe_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skurecipe',
            name='machine_name',
        ),
    ]
