# Generated by Django 6.0.4 on 2026-04-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0015_alter_planningjob_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='skurecipe',
            name='machine_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
