# Generated by Django 6.0.4 on 2026-05-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0016_skurecipe_machine_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planningjob',
            name='awc_no',
        ),
        migrations.RemoveField(
            model_name='planningjob',
            name='die_cutting',
        ),
        migrations.RemoveField(
            model_name='planningjob',
            name='purchase_material',
        ),
        migrations.RemoveField(
            model_name='skurecipe',
            name='machine_name',
        ),
        migrations.RemoveField(
            model_name='skurecipe',
            name='plate_set_no',
        ),
        migrations.RemoveField(
            model_name='skurecipe',
            name='purchase_material',
        ),
        migrations.AddField(
            model_name='planningjob',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planningjob',
            name='purchase_material_origin',
            field=models.CharField(blank=True, choices=[('', 'Select Origin'), ('local', 'Local'), ('import', 'Import')], max_length=20),
        ),
    ]
