# Generated by Django 6.0.4 on 2026-06-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0018_add_job_card_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='planningjob',
            name='planning_stage',
            field=models.CharField(blank=True, choices=[('', 'Not Set'), ('jc_ready', 'JC Ready'), ('new_plate_making', 'New Plate Making'), ('repeat_plate_making', 'Repeat Plate Making')], default='', max_length=40),
        ),
    ]
