# Generated by Django 6.0.4 on 2026-06-03 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0019_planningjob_planning_stage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='planningjob',
            name='change_request_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planningjob',
            name='change_request_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='planningjob',
            name='change_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planningjob',
            name='change_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_jobs_change_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='planningjob',
            name='planning_stage',
            field=models.CharField(blank=True, choices=[('', 'Not Set'), ('jc_ready', 'JC Ready'), ('new_plate_making', 'New Plate Making'), ('repeat_plate_making', 'Repeat Plate Making'), ('in_production', 'In Production')], default='', max_length=40),
        ),
    ]
