# Generated by Django 6.0.4 on 2026-06-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0020_planningjob_change_request_pending_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planningjob',
            name='po_approval_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
