# Generated by Django 6.0.4 on 2026-06-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0021_planningjob_po_approval_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planningjob',
            name='purchase_sheet_ups',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='planningjob',
            name='ups',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='skurecipe',
            name='purchase_sheet_ups',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='skurecipe',
            name='ups',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
