# Generated by Django 6.0.4 on 2026-06-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0022_alter_planningjob_purchase_sheet_ups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planningjob',
            name='planning_stage_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
