# Generated by Django 6.0.4 on 2026-06-29 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0025_planningjob_master_sync_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCardChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_wastage_sheets', models.PositiveIntegerField(blank=True, null=True)),
                ('proposed_wastage_sheets', models.PositiveIntegerField(blank=True, null=True)),
                ('current_machine_name', models.CharField(blank=True, max_length=120)),
                ('proposed_machine_name', models.CharField(blank=True, max_length=120)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending PM Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_job_changes', to=settings.AUTH_USER_MODEL)),
                ('planning_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wastage_machine_change_requests', to='planning.planningjob')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_job_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
