# Generated by Django 6.0.4 on 2026-06-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0025_planningjob_master_sync_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planningjob',
            name='planning_stage',
            field=models.CharField(blank=True, choices=[('', 'Not Set'), ('jc_ready', 'JC Ready'), ('new_plate_making', 'New Plate Making'), ('repeat_plate_making', 'Repeat Plate Making'), ('plate_received', 'Plate Received'), ('in_production', 'In Production')], default='', max_length=40),
        ),
    ]
