# Generated by Django 6.0.4 on 2026-07-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0026_alter_planningjob_planning_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='skurecipe',
            name='machine_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='skurecipe',
            name='plate_set_no',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
