# Generated by Django 6.0.4 on 2026-07-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0027_skurecipe_machine_name_skurecipe_plate_set_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='skurecipe',
            name='remarks',
            field=models.TextField(blank=True),
        ),
    ]
