# Generated by Django 6.0.4 on 2026-07-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0028_skurecipe_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planningjob',
            name='daily_demand',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='planningjob',
            name='purchase_sheet_ups',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planningjob',
            name='size_h_mm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planningjob',
            name='size_w_mm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planningjob',
            name='stock_bag',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='planningjob',
            name='stock_qty',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='planningjob',
            name='ups',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skurecipe',
            name='daily_demand',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='skurecipe',
            name='purchase_sheet_ups',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skurecipe',
            name='size_h_mm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skurecipe',
            name='size_w_mm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skurecipe',
            name='ups',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
