# Generated by Django 6.0.4 on 2026-06-29 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0030_jobcardchangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcardchangerequest',
            name='request_type',
            field=models.CharField(default='reopen_to_draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobcardchangerequest',
            name='current_machine_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='jobcardchangerequest',
            name='planning_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='planning.planningjob'),
        ),
        migrations.AlterField(
            model_name='jobcardchangerequest',
            name='proposed_machine_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='jobcardchangerequest',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
