# Generated by Django 6.0.4 on 2026-07-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0039_skurecipe_print_passes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planningjob',
            name='print_passes',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of press passes (1, 2, 3, or 4). Total impressions = print sheets × passes.', null=True),
        ),
        migrations.AlterField(
            model_name='skurecipe',
            name='print_passes',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of press passes (1, 2, 3, or 4) for Print + Pack SKUs.', null=True),
        ),
    ]
