# Generated by Django 6.0.4 on 2026-07-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0040_alter_planningjob_print_passes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planningjob',
            name='priority',
            field=models.IntegerField(choices=[(0, 'Low'), (1, 'Normal'), (2, 'Medium'), (3, 'High'), (4, 'Urgent')], db_index=True, default=1),
        ),
    ]
