# Generated by Django 6.0.4 on 2026-07-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0041_planningjob_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='skurecipe',
            name='machine_name_locked',
            field=models.BooleanField(default=False, help_text='When set, actual production machine tracking will not auto-update machine_name for this SKU.'),
        ),
    ]
