# Generated by Django 5.2.16 on 2026-07-21 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0042_skurecipe_machine_name_locked'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='planningjob',
            name='cancel_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='planningjob',
            name='cancel_reason_code',
            field=models.CharField(blank=True, choices=[('customer_cancelled', 'Customer Cancelled the SKU'), ('po_amended', 'PO Amended / Quantity Removed'), ('duplicate_entry', 'Duplicate Planning Entry'), ('superseded', 'Superseded by Another Job'), ('other', 'Other')], max_length=40),
        ),
        migrations.AddField(
            model_name='planningjob',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planningjob',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_jobs_cancelled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planningjob',
            name='is_cancelled',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='planningjob',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('pending_qc', 'Pending QC'), ('qc_approved', 'QC Approved'), ('released', 'Released'), ('in_production', 'In Production'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=40),
        ),
    ]
