# Generated by Django 5.2.16 on 2026-07-21 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0043_planningjob_cancel_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MergeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('artwork_requested', 'Artwork Requested'), ('artwork_ready', 'Artwork Ready'), ('layout_done', 'Layout Done'), ('cancelled', 'Cancelled')], db_index=True, default='accepted', max_length=30)),
                ('print_sheet_size', models.CharField(blank=True, max_length=80)),
                ('material', models.CharField(blank=True, max_length=120)),
                ('total_sheet_ups', models.PositiveIntegerField(blank=True, null=True)),
                ('run_sheets', models.PositiveIntegerField(blank=True, null=True)),
                ('total_colors', models.PositiveIntegerField(blank=True, null=True)),
                ('plates_saved', models.IntegerField(default=0)),
                ('makereadies_saved', models.IntegerField(default=0)),
                ('impressions_saved', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('designer_notes', models.TextField(blank=True)),
                ('designer_requested_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merge_groups_accepted', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merge_groups_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MergeGroupItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_ups', models.PositiveIntegerField()),
                ('planned_produced_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('net_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('overage_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('merge_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='planning.mergegroup')),
                ('planning_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_items', to='planning.planningjob')),
            ],
            options={
                'ordering': ['-allocated_ups', 'id'],
                'unique_together': {('merge_group', 'planning_job')},
            },
        ),
    ]
