# Generated by Django 5.2.16 on 2026-07-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0044_mergegroup_mergegroupitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='mergegroup',
            name='artwork_code',
            field=models.CharField(blank=True, help_text='Combined artwork code for the merged layout, e.g. AWC-MG-2026-0001.', max_length=40),
        ),
        migrations.AddField(
            model_name='mergegroup',
            name='mr_minutes_saved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mergegroup',
            name='setup_sheets_saved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mergegroupitem',
            name='source_awc_no',
            field=models.CharField(blank=True, help_text="The SKU's own artwork code at the time of merging, so the designer can find the source file.", max_length=120),
        ),
    ]
