# Generated by Django 5.2.16 on 2026-07-21 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0045_mergegroup_artwork_code_mergegroup_mr_minutes_saved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mergegroup',
            name='lead_job',
            field=models.ForeignKey(blank=True, help_text='The job that carries the shared plate request and printing run for the whole group.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_merge_groups', to='planning.planningjob'),
        ),
        migrations.AddField(
            model_name='mergegroupitem',
            name='is_lead',
            field=models.BooleanField(default=False),
        ),
    ]
