# Generated by Django 5.2.16 on 2026-07-22 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0047_backfill_merge_group_lead'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mergegroup',
            name='layout_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mergegroup',
            name='layout_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merge_groups_layout_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mergegroup',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('layout_approved', 'Layout Approved for Production'), ('artwork_requested', 'Artwork Requested'), ('artwork_ready', 'Artwork Ready'), ('layout_done', 'Layout Done'), ('cancelled', 'Cancelled')], db_index=True, default='accepted', max_length=30),
        ),
    ]
