# Generated by Django 5.2.16 on 2026-07-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0048_mergegroup_layout_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mergegroup',
            name='combined_wastage_sheets',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mergegroup',
            name='purchase_material_origin',
            field=models.CharField(blank=True, choices=[('', 'Select Origin'), ('local', 'Local'), ('import', 'Import')], max_length=20),
        ),
    ]
