# Generated by Django 6.0.4 on 2026-07-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0049_mergegroup_combined_wastage_sheets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mergegroup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mergegroupitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
