# Generated by Django 5.2.16 on 2026-08-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0051_delete_jobcardlayout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planningjob',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='planningjob',
            name='po_number',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='planningjob',
            name='sku',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='planningjob',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('pending_qc', 'Pending QC'), ('qc_approved', 'QC Approved'), ('released', 'Released'), ('in_production', 'In Production'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=40),
        ),
    ]
