# Generated by Django 5.2.16 on 2026-09-15 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0052_add_planning_job_perf_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='planningjob',
            name='form_label',
            field=models.CharField(blank=True, help_text="Name of this form/ply within its group, e.g. 'White', 'Pink', 'Cover'.", max_length=50),
        ),
        migrations.AddField(
            model_name='planningjob',
            name='parent_planning_job',
            field=models.ForeignKey(blank=True, help_text="Set when this planning job is one form/ply of a multi-form book job (e.g. an NCR ply). Points to the group's root planning job.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_forms', to='planning.planningjob'),
        ),
        migrations.AddField(
            model_name='planningjob',
            name='pcs_per_unit',
            field=models.PositiveIntegerField(default=1, help_text='Pieces per order unit. 500 for rim-based jobs (1 rim = 500 pcs); 1 for standard pcs jobs.'),
        ),
        migrations.AddField(
            model_name='planningjob',
            name='unit_type',
            field=models.CharField(choices=[('pcs', 'Pieces'), ('rim', 'Rims')], default='pcs', max_length=10),
        ),
    ]
