# Generated by Django 5.2.16 on 2026-09-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0053_planningjob_form_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skurecipe',
            name='default_form_labels',
            field=models.CharField(blank=True, help_text="Comma-separated ply/form names for a multi-form book SKU, e.g. 'White,Pink,Yellow' for a triplicate NCR book. Leave blank for a normal single-form job. When set, creating a job for this SKU also creates one sibling job card per extra label.", max_length=255),
        ),
        migrations.AddField(
            model_name='skurecipe',
            name='pcs_per_unit',
            field=models.PositiveIntegerField(default=1, help_text="Pieces per order unit when unit_type='rim' (500 for 1 rim = 500 pcs). Ignored for 'pcs'."),
        ),
        migrations.AddField(
            model_name='skurecipe',
            name='unit_type',
            field=models.CharField(choices=[('pcs', 'Pieces'), ('rim', 'Rims')], default='pcs', help_text='Order-qty unit for jobs using this SKU. A PO always states the quantity as a plain number — this is what tells the system to read it as rims (e.g. A4 paper) instead of pieces.', max_length=10),
        ),
    ]
