# Generated by Django 5.2.16 on 2026-09-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0054_skurecipe_default_form_labels_skurecipe_pcs_per_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planningjob',
            name='pcs_per_unit',
            field=models.PositiveIntegerField(default=1, help_text='Pieces per order unit — 500 for a rim, pages-per-book for a book SKU, etc; 1 for standard pcs jobs.'),
        ),
        migrations.AlterField(
            model_name='planningjob',
            name='unit_type',
            field=models.CharField(choices=[('pcs', 'Pieces'), ('rim', 'Rims'), ('book', 'Books'), ('box', 'Boxes')], default='pcs', max_length=10),
        ),
        migrations.AlterField(
            model_name='skurecipe',
            name='unit_type',
            field=models.CharField(choices=[('pcs', 'Pieces'), ('rim', 'Rims'), ('book', 'Books'), ('box', 'Boxes')], default='pcs', help_text="Order-qty unit for jobs using this SKU, matching the unit the customer's WO/PO actually orders in for this SKU (their PO's own unit label can't be trusted — it's often just 'PIECE' regardless of whether the real unit is a sheet, a rim, or a book). Declared once here; every job for this SKU then inherits it.", max_length=10),
        ),
    ]
