# Generated by Django 5.2.16 on 2026-09-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0055_alter_planningjob_skurecipe_unit_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skurecipe',
            name='default_form_labels',
            field=models.CharField(blank=True, help_text="Comma-separated form names for a multi-form book SKU. Leave blank for a normal single-form job; creating a job for this SKU then also creates one sibling job card per extra label. Two styles: 'White,Pink,Yellow' for a uniform book (e.g. an NCR triplicate — every ply has the same page count, taken from Pieces per Order Unit above); 'Cover:2,Inner:10' for a book whose forms are different content/stock with DIFFERENT page counts each (e.g. a booklet's cover vs its inner pages) — the number after the colon overrides Pieces per Order Unit for just that one form.", max_length=255),
        ),
    ]
