# Generated by Django 6.0.4 on 2026-10-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0057_alter_skurecipe_default_form_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skurecipe',
            name='default_form_labels',
            field=models.CharField(blank=True, help_text="Comma-separated form names for a multi-form book SKU. Leave blank for a normal single-form job; creating a job for this SKU then also creates one sibling job card per extra label. Each form is 'Label', 'Label:pages', 'Label:pages:ups', 'Label:pages:ups:passes', or 'Label:pages:ups:passes:material' — every part after Label is optional and left blank inherits from Pieces per Order Unit / UPS / No. of Passes / Material Type above. 'White,Pink,Yellow' is a uniform book (e.g. an NCR triplicate — every ply shares the same page count/ups/passes); 'White::::NCR White,Pink::::NCR Pink,Yellow::::NCR Yellow' gives each ply its own paper. 'Cover:2:1:1,Inner:10:2:5' is a heterogeneous book (e.g. a booklet's cover — 2 pages, 1-up, 1 pass — vs its inner pages — 10 pages, 2-up, 5 passes) where each form differs.", max_length=500),
        ),
    ]
