# Generated by Django 5.2.16 on 2026-07-30 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_machine_planning_jc_selection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPITarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpi_slug', models.CharField(choices=[('order_fulfillment', 'Order Fulfillment Efficiency'), ('wastage_reduction', 'Wastage Reduction Efficiency'), ('dispatch_alignment', 'Dispatch vs Production Alignment')], max_length=40)),
                ('year', models.PositiveIntegerField()),
                ('position', models.CharField(blank=True, max_length=120)),
                ('objective', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('description', models.TextField(blank=True)),
                ('uom', models.CharField(default='%', max_length=20)),
                ('weightage_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('monitoring_frequency', models.CharField(default='Quarterly', max_length=20)),
                ('min_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('higher_is_better', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-year', 'kpi_slug'],
                'unique_together': {('kpi_slug', 'year')},
            },
        ),
        migrations.CreateModel(
            name='KPIActionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpi_slug', models.CharField(choices=[('order_fulfillment', 'Order Fulfillment Efficiency'), ('wastage_reduction', 'Wastage Reduction Efficiency'), ('dispatch_alignment', 'Dispatch vs Production Alignment')], max_length=40)),
                ('period_type', models.CharField(choices=[('month', 'Month'), ('quarter', 'Quarter')], max_length=10)),
                ('period_key', models.CharField(max_length=10)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('kpi_slug', 'period_type', 'period_key')},
            },
        ),
    ]
