# Generated by Django 5.2.16 on 2026-08-11 05:13

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotAutomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Stable identifier used for seeding/lookup, e.g. PENDING_PRODUCTION_RELEASE.', max_length=80, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False, help_text='Only active bots are picked up by the scheduler. Preview and test-send first.')),
                ('report_slug', models.CharField(db_index=True, help_text='Slug of a report registered in reports.report_registry (e.g. pending-work).', max_length=120)),
                ('report_filters', models.JSONField(blank=True, default=dict, help_text='Filters passed to the report, e.g. {"stage": "not_released"}.')),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='DAILY', max_length=10)),
                ('send_time', models.TimeField(default=datetime.time(8, 30))),
                ('weekdays', models.CharField(blank=True, help_text='Comma-separated weekday numbers (0=Mon .. 6=Sun). Blank means every day.', max_length=20)),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, help_text='Day of month for MONTHLY frequency (1-31). Clamped to the last day of short months.', null=True)),
                ('start_date', models.DateField(blank=True, help_text='Optional: do not run before this date.', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Optional: do not run after this date.', null=True)),
                ('email_to', models.TextField(blank=True, help_text='Comma or newline separated addresses.')),
                ('email_cc', models.TextField(blank=True)),
                ('email_bcc', models.TextField(blank=True)),
                ('recipient_roles', models.CharField(blank=True, help_text='Comma-separated role keys (e.g. planner,production_manager). Resolved to live user emails at send time.', max_length=255)),
                ('subject_template', models.CharField(default='Pending Work - Required for Production Release - {{date}}', max_length=255)),
                ('body_template', models.TextField(default='<p>Dear Planning Team,</p>\n\n<p>Please find below the pending work that is required to be released\nfor production.</p>\n\n{{report_table}}\n\n<p>Kindly review and release the pending jobs as per priority.</p>\n\n<p>Regards,<br>\nProduction Printing</p>\n')),
                ('max_rows_in_body', models.PositiveIntegerField(default=100, help_text='Rows shown inline in the email body. The rest go in the attachment.')),
                ('attach_report', models.BooleanField(default=True)),
                ('attachment_format', models.CharField(choices=[('xlsx', 'Excel (.xlsx)'), ('csv', 'CSV (.csv)'), ('pdf', 'PDF (.pdf)')], default='xlsx', max_length=10)),
                ('send_when_empty', models.BooleanField(default=False, help_text='Send the email even when the report returns zero rows.')),
                ('retry_count', models.PositiveSmallIntegerField(default=2, help_text='Extra attempts after a failed run, within the same day.')),
                ('retry_interval_minutes', models.PositiveIntegerField(default=15, help_text='Minimum wait before retrying a failed run.')),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_status', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bots_created', to=settings.AUTH_USER_MODEL)),
                ('run_as', models.ForeignKey(blank=True, help_text="Report runs with this user's permissions. Defaults to the first superuser.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bots_run_as', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bot Automation',
                'verbose_name_plural': 'Bot Automations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BotExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('AUTO', 'Scheduled'), ('MANUAL', 'Run Now'), ('TEST', 'Test Send')], default='AUTO', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Running'), ('SENT', 'Sent'), ('SKIPPED', 'Skipped (no records)'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('record_count', models.IntegerField(blank=True, null=True)),
                ('recipients_to', models.TextField(blank=True)),
                ('recipients_cc', models.TextField(blank=True)),
                ('recipients_bcc', models.TextField(blank=True)),
                ('rendered_subject', models.CharField(blank=True, max_length=255)),
                ('rendered_body', models.TextField(blank=True)),
                ('attachment_name', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='bot.botautomation')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_executions_triggered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bot Execution',
                'verbose_name_plural': 'Bot Executions',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['bot', '-started_at'], name='bot_botexec_bot_id_967abf_idx'), models.Index(fields=['status', '-started_at'], name='bot_botexec_status_2546ee_idx')],
            },
        ),
    ]
