# Generated by Django 5.2.16 on 2026-08-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botautomation',
            name='report_date_from',
            field=models.DateField(blank=True, help_text='Start of the range when the period is Custom Range.', null=True),
        ),
        migrations.AddField(
            model_name='botautomation',
            name='report_date_to',
            field=models.DateField(blank=True, help_text='End of the range when the period is Custom Range.', null=True),
        ),
        migrations.AddField(
            model_name='botautomation',
            name='report_period',
            field=models.CharField(blank=True, choices=[('', 'Report default'), ('today', 'Today'), ('week', 'This Week'), ('month', 'This Month'), ('custom', 'Custom Range'), ('all', 'All Time')], default='', help_text="Date range the report covers, same presets as the report screen. Blank leaves the report's own default (current month).", max_length=10),
        ),
    ]
