# Generated by Django 5.2.16 on 2026-08-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_botautomation_report_date_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botautomation',
            name='report_period',
            field=models.CharField(blank=True, choices=[('', 'Report default'), ('today', 'Today'), ('yesterday', 'Yesterday'), ('week', 'This Week'), ('month', 'This Month'), ('custom', 'Custom Range'), ('all', 'All Time')], default='', help_text="Date range the report covers, same presets as the report screen. Blank leaves the report's own default (current month).", max_length=10),
        ),
    ]
