# Generated by Django 5.2.16 on 2026-08-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_botautomation_report_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='botautomation',
            name='use_ai_summary',
            field=models.BooleanField(default=False, help_text="Prepend a short AI-generated plain-English summary paragraph above the report table. Uses the local LLM; if it's unreachable or times out, the email still sends without the summary."),
        ),
    ]
