# Generated by Django 5.2.16 on 2026-07-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('shift', models.CharField(blank=True, choices=[('A', 'Shift A'), ('B', 'Shift B')], max_length=1, null=True)),
                ('target_qty', models.PositiveIntegerField(help_text='Target output in pcs for the date (and shift, if set)')),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('date', 'shift'), name='unique_daily_target_per_shift')],
            },
        ),
    ]
