# Generated by Django 5.2.16 on 2026-08-18 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_email_enabled', models.BooleanField(default=True, help_text='Send an email immediately when a task is assigned/reassigned to a user or team.')),
                ('reminders_enabled', models.BooleanField(default=True, help_text='Send recurring reminder emails for pending/in-progress tasks.')),
                ('reminder_interval_days', models.PositiveSmallIntegerField(default=3, help_text='Days between reminder emails for the same task.')),
                ('remind_from', models.CharField(choices=[('assignment', 'From the moment the task is assigned'), ('overdue', 'Only once the task is overdue (past due date)')], default='assignment', help_text='Whether the reminder clock starts at assignment or only once the task is overdue.', max_length=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task Notification Settings',
                'verbose_name_plural': 'Task Notification Settings',
            },
        ),
        migrations.CreateModel(
            name='TaskReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed')], default='SENT', max_length=10)),
                ('recipients', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='tasks.task')),
            ],
            options={
                'verbose_name': 'Task Reminder Log',
                'verbose_name_plural': 'Task Reminder Logs',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['task', '-sent_at'], name='tasks_taskr_task_id_ab9a58_idx')],
            },
        ),
    ]
