# Generated by Django 6.0.4 on 2026-07-19 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0070_seed_application_types'),
        ('supply_chain', '0012_itemrequestquote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaultCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_no', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Record No.')),
                ('reported_date', models.DateField()),
                ('maintenance_type', models.CharField(choices=[('PREVENTIVE', 'Preventive'), ('CORRECTIVE', 'Corrective'), ('BREAKDOWN', 'Breakdown'), ('PREDICTIVE', 'Predictive')], max_length=20)),
                ('execution_type', models.CharField(choices=[('IN_HOUSE', 'In-house'), ('OUTSOURCE', 'Outsource')], default='IN_HOUSE', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('MAJOR', 'Major'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('fault_description', models.TextField()),
                ('proposed_solution', models.TextField(blank=True)),
                ('spare_parts_needed', models.BooleanField(default=False)),
                ('repair_needed', models.BooleanField(default=False)),
                ('repair_details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('REPORTED', 'Reported'), ('DIAGNOSED', 'Diagnosed'), ('AWAITING_PARTS', 'Awaiting Parts'), ('AWAITING_VENDOR', 'Awaiting Vendor'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('VERIFIED', 'Verified'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], db_index=True, default='REPORTED', max_length=20)),
                ('work_start_at', models.DateTimeField(blank=True, null=True)),
                ('work_end_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_records_assigned', to=settings.AUTH_USER_MODEL)),
                ('fault_types', models.ManyToManyField(blank=True, related_name='maintenance_records', to='maintenance.faultcategory')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='core.machine')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records_reported', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reported_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(blank=True, max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_log', to='maintenance.maintenancerecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MachineDowntime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(choices=[('BREAKDOWN', 'Breakdown'), ('PLANNED_PM', 'Planned PM'), ('AWAITING_PART', 'Awaiting Part'), ('AWAITING_VENDOR', 'Awaiting Vendor'), ('OTHER', 'Other')], default='BREAKDOWN', max_length=20)),
                ('scheduled_minutes_lost', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='downtime_intervals', to='core.machine')),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downtime_intervals', to='maintenance.maintenancerecord')),
            ],
            options={
                'ordering': ['-start_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceServiceJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(blank=True, max_length=150)),
                ('scope', models.TextField()),
                ('sent_out_date', models.DateField(blank=True, null=True)),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_service_jobs', to='supply_chain.itemrequest')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_jobs', to='maintenance.maintenancerecord')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceSparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('uom', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('existing_sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_spare_lines', to='supply_chain.rawmaterialsku')),
                ('item_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_spare_lines', to='supply_chain.itemrequest')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spare_parts', to='maintenance.maintenancerecord')),
            ],
        ),
    ]
