# Generated by Django 5.2.16 on 2026-08-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_maintenancerecord_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerecord',
            name='maintenance_type',
            field=models.CharField(blank=True, choices=[('PREVENTIVE', 'Preventive'), ('CORRECTIVE', 'Corrective'), ('BREAKDOWN', 'Breakdown'), ('PREDICTIVE', 'Predictive')], default='', max_length=20),
        ),
    ]
