# Generated by Django 6.0.4 on 2026-05-14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('PLANNING', 'Planning'), ('PRODUCTION', 'Production'), ('DISPATCH', 'Dispatch')], max_length=20)),
                ('sheet_url', models.URLField(max_length=1024)),
                ('status', models.CharField(choices=[('STAGED', 'Staged'), ('VALIDATED', 'Validated'), ('PARTIAL', 'Partially Imported'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='STAGED', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('error_rows', models.PositiveIntegerField(default=0)),
                ('imported_rows', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migration_jobs_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('view_import', 'Can view migration import module'), ('run_import', 'Can run migration imports')],
            },
        ),
        migrations.CreateModel(
            name='MigrationImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rows_count', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='migration.migrationimportjob')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migration_import_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanningImportStaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('po_number', models.CharField(blank=True, max_length=120)),
                ('customer', models.CharField(blank=True, max_length=255)),
                ('sku', models.CharField(blank=True, max_length=255)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('import_status', models.CharField(choices=[('PENDING', 'Pending'), ('VALID', 'Valid'), ('ERROR', 'Error'), ('IMPORTED', 'Imported')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('imported_reference', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_rows', to='migration.migrationimportjob')),
            ],
            options={
                'ordering': ['row_number', 'id'],
                'unique_together': {('import_job', 'row_number')},
            },
        ),
    ]
