# Generated by Django 6.0.4 on 2026-05-14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('PO_INTAKE', 'PO Intake'), ('SKU_MASTER', 'SKU Master'), ('JOB_FINALIZE', 'Job Finalize'), ('PLANNING', 'Planning'), ('PRODUCTION', 'Production'), ('DISPATCH', 'Dispatch')], max_length=30)),
                ('sheet_url', models.URLField(max_length=1024)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('REVIEW', 'Review Required'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('total_columns', models.PositiveIntegerField(default=0)),
                ('matched_columns', models.PositiveIntegerField(default=0)),
                ('missing_columns', models.PositiveIntegerField(default=0)),
                ('extra_columns', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comparison_jobs_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComparisonResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_column', models.CharField(max_length=255)),
                ('erp_model', models.CharField(blank=True, max_length=255)),
                ('erp_field', models.CharField(blank=True, max_length=255)),
                ('match_type', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(blank=True, max_length=30)),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('details', models.TextField(blank=True)),
                ('sample_values', models.JSONField(blank=True, default=list)),
                ('comparison_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='migration.comparisonjob')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ColumnMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(blank=True, max_length=120)),
                ('sheet_column', models.CharField(max_length=255)),
                ('erp_model', models.CharField(blank=True, max_length=255)),
                ('erp_field', models.CharField(blank=True, max_length=255)),
                ('match_confidence', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comparison_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_mappings', to='migration.comparisonjob')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='column_mappings_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['comparison_job', 'sheet_column'],
                'unique_together': {('comparison_job', 'sheet_column')},
            },
        ),
    ]
