# Generated by Django 5.2.16 on 2026-09-09 15:09

from django.db import migrations, models


def mark_existing_lines_as_formula(apps, schema_editor):
    """Every BomTemplateLine created before this migration was necessarily
    authored as a qty_expression (the field was required pre-migration) — the
    new entry_mode='simple' default is only correct for lines created from now
    on via the Recipe Wizard / quick-entry form."""
    BomTemplateLine = apps.get_model('bom', 'BomTemplateLine')
    BomTemplateLine.objects.filter(qty_expression__gt='').update(entry_mode='formula')


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomtemplateline',
            name='entry_mode',
            field=models.CharField(choices=[('simple', 'Simple (plain number)'), ('formula', 'Formula')], default='simple', help_text='Simple: type a fixed qty/wastage for this exact spec combination. Formula: an expression that scales across every size/spec matching this template.', max_length=10),
        ),
        migrations.AddField(
            model_name='bomtemplateline',
            name='fixed_qty',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Used when entry_mode=simple: consumption per one FG unit.', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='bomtemplateline',
            name='fixed_wastage_percent',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Used when entry_mode=simple: e.g. 0.05 for 5%.', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='bomtemplateline',
            name='qty_expression',
            field=models.CharField(blank=True, help_text='Used when entry_mode=formula: evaluated against the SKU spec + line_qty() of prior lines.', max_length=500),
        ),
        migrations.AlterField(
            model_name='bomtemplateline',
            name='wastage_expression',
            field=models.CharField(blank=True, default='0', help_text='Used when entry_mode=formula: formula or constant, e.g. 0.05.', max_length=200),
        ),
        migrations.RunPython(mark_existing_lines_as_formula, noop_reverse),
    ]
