# Generated by Django 5.2.16 on 2026-09-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0002_bomtemplateline_entry_mode_bomtemplateline_fixed_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specattribute',
            name='is_wizard_step',
            field=models.BooleanField(default=False, help_text='Shown as a cascade step in the Recipe Wizard (in sort_order). Leave off for refinement attributes (e.g. GSM, total colors) that are still valid template match keys but implied by an earlier step.'),
        ),
    ]
