"""
Django settings for Offset_ERP project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

REDIS_URL = os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379')

# Password reset / new-account emails go out over Gmail SMTP. Credentials can
# be set from Settings -> Roles & Access Control (stored in the EmailSettings
# DB row, no restart needed) or via GMAIL_ADDRESS/GMAIL_APP_PASSWORD env vars
# as a fallback. See core/email_backend.py — it reads whichever is present at
# send-time and prints to the console instead of sending when neither is set.
EMAIL_BACKEND = 'core.email_backend.DynamicGmailEmailBackend'
DEFAULT_FROM_EMAIL = os.environ.get('GMAIL_ADDRESS', 'no-reply@offsetprintingerp.local')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^*pvqm&za4c4%6$bnc+0i22xcl)r6oy(p(ar#vxsm80^cc-6_@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Self-signed HTTPS is served directly by Daphne on 8000 (see DEPLOYMENT.md) so
# that WebRTC's getUserMedia works from LAN clients other than the server box
# itself (browsers require a secure context — https or localhost — for camera/
# mic access). Django enforces Origin-header checking on unsafe HTTP methods,
# so the https origin needs to be explicitly trusted here.
CSRF_TRUSTED_ORIGINS = os.environ.get(
    'CSRF_TRUSTED_ORIGINS',
    'https://192.168.88.30:8000',
).split(',')

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Application definition

INSTALLED_APPS = [
    'daphne',  # must precede staticfiles so Channels' runserver substitution takes effect
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.humanize',
    'django.contrib.staticfiles',
    'channels',
    'rest_framework',
    'core',
    'planning',
    'printing_plates',
    'migration',
    'qc',
    'workflow',
    'manual_working',
    'reports',
    'theme',
    'production',
    'supply_chain',
    'job_summary',
    'audit',
    'tasks',
    'backup',
    'maintenance',
    'floor_dashboard',
    'chat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Offset_ERP.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'core/templates',
            BASE_DIR / 'Job_card_html',
            BASE_DIR / 'printing_plates/templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.software_version',
                'core.context_processors.navigation_permissions',
            ],
        },
    },
]

WSGI_APPLICATION = 'Offset_ERP.wsgi.application'
ASGI_APPLICATION = 'Offset_ERP.asgi.application'

# NOTE: the Redis instance already running on this dev machine is v5.0.14, which
# predates the RESP3 HELLO handshake (Redis 6+) that redis-py negotiates by
# default — hence `protocol: 2` (RESP2) below. Drop this once Redis is upgraded.
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [{
                'address': f'{REDIS_URL}/0',
                'protocol': 2,
                'socket_connect_timeout': 5,
                'socket_timeout': 10,
                'retry_on_timeout': True,
            }],
            'capacity': 1500,
            'expiry': 60,
            'channel_capacity': {
                'chat_presence': 200,
            },
        },
    },
}

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': f'{REDIS_URL}/1',
        'OPTIONS': {
            'protocol': 2,
        },
    },
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.CursorPagination',
    'PAGE_SIZE': 30,
}


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / "db.sqlite3",
        'OPTIONS': {
            'init_command': (
                'PRAGMA journal_mode=WAL; '
                'PRAGMA busy_timeout=5000; '
                'PRAGMA synchronous=NORMAL; '
                'PRAGMA temp_store=MEMORY; '
                'PRAGMA cache_size=-2000;'
            ),
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Karachi'

USE_I18N = True

USE_TZ = True

# Authentication
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'

# ERP software version information
ERP_SOFTWARE_VERSION = '2026.07.03.1'
ERP_SOFTWARE_RELEASE_DATE = '2026-07-03'

# Lock older operational records from edit for non-managerial roles.
ERP_RECORD_EDIT_LOCK_DAYS = 2

# Chat module
CHAT_ICE_SERVERS = [
    {'urls': ['stun:stun.l.google.com:19302']},
    # Future (remote/VPN users): add a TURN entry here, e.g.
    # {'urls': ['turn:lan-turn-server:3478'], 'username': '...', 'credential': '...'}
]
CHAT_MEDIA_SUBDIR = 'chat_media'
CHAT_MAX_ATTACHMENT_MB = 25
CHAT_ATTACHMENT_RETENTION_DAYS = 180
CHAT_MESSAGE_EDIT_WINDOW_MINUTES = 15

