"""
Django settings for Offset_ERP project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

REDIS_URL = os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379')

# Password reset / new-account emails go out over Gmail SMTP. Credentials can
# be set from Settings -> Roles & Access Control (stored in the EmailSettings
# DB row, no restart needed) or via GMAIL_ADDRESS/GMAIL_APP_PASSWORD env vars
# as a fallback. See core/email_backend.py — it reads whichever is present at
# send-time and prints to the console instead of sending when neither is set.
EMAIL_BACKEND = 'core.email_backend.DynamicGmailEmailBackend'
DEFAULT_FROM_EMAIL = os.environ.get('GMAIL_ADDRESS', 'no-reply@offsetprintingerp.local')

# Base URL used to build absolute links inside emails sent from background code
# with no `request` object (task assignment/reminder emails — see tasks/emails.py).
TASK_APP_BASE_URL = os.environ.get('TASK_APP_BASE_URL', 'https://offseterp.duckdns.org')
# Opt-out for the in-process task reminder scheduler thread (tasks/scheduler.py),
# defaulting to ON like BOT_INPROCESS_SCHEDULER. Set False to disable.
TASK_REMINDER_INPROCESS_SCHEDULER = os.environ.get('TASK_REMINDER_INPROCESS_SCHEDULER', 'True') == 'True'
# Opt-out for the in-process bot/automation scheduler thread (bot/scheduler.py),
# same pattern as TASK_REMINDER_INPROCESS_SCHEDULER above. Set False on any
# server that must never execute scheduled sends itself — critically, the DR
# standby (offseterpbackup.duckdns.org), which receives a live copy of the
# primary's database (including real, active bot rows with real recipients)
# via scripts/cloud/standby/cron_sync_standby_from_primary.sh but must stay
# passive. Without this, the standby's own web container independently fires
# every due automation a second time.
BOT_INPROCESS_SCHEDULER = os.environ.get('BOT_INPROCESS_SCHEDULER', 'True') == 'True'
# Same per-server kill switch, for the backup scheduler (backup/scheduler.py).
# Backups are also DB-driven (BackupSetting.backup_enabled) and that row is
# part of the synced database too, so — same reasoning as the two above —
# only an env var can durably keep the standby from taking its own redundant
# backup runs regardless of what backup_enabled says in the synced copy.
BACKUP_INPROCESS_SCHEDULER = os.environ.get('BACKUP_INPROCESS_SCHEDULER', 'True') == 'True'

# Local LLM (LM Studio, OpenAI-compatible chat endpoint). Never hardcode the
# endpoint elsewhere — everything routes through these settings so pointing
# at a different host later (e.g. an Oracle VM) is a config change, not a
# code change. See core/llm/client.py.
LLM_ENABLED = os.environ.get('LLM_ENABLED', 'True') == 'True'
LLM_ENDPOINT_URL = os.environ.get('LLM_ENDPOINT_URL', 'http://127.0.0.1:1234')
# ibm-granite/granite-4.0-micro: winner of a 4-way benchmark on this app's
# real prompts (core/management/commands/llm_benchmark.py), avg 22.8s with
# ZERO reasoning tokens on every call — it's not a "thinking" model at all,
# so there's no hidden chain-of-thought overhead to strip or wait out.
# Runner-up nvidia/nemotron-3-nano-4b averaged 38.1s (still does some light
# reasoning, ~15-280 tokens/call). qwen3-4b-thinking averaged 124.6s
# (~400-1000 reasoning tokens/call — avoid anything tagged "thinking" for
# this app's use case, phrasing already-fetched facts needs no reasoning).
# google/gemma-4-e4b skips reasoning too but is slower per-token on this
# iGPU (47.2s avg). Re-run llm_benchmark before changing this again — don't
# guess from token counts alone, per-token speed varies by model on this
# hardware.
LLM_MODEL_ID = os.environ.get('LLM_MODEL_ID', 'granite-4.0-micro')
# core/llm/client.py defaults max_tokens generously (4000) as a safety
# ceiling regardless of model — it stops on its own once done, so a high
# ceiling doesn't slow down the common case, it just avoids truncating an
# unusually slow run. Timeout is set to match that worst case.
LLM_TIMEOUT_SECONDS = float(os.environ.get('LLM_TIMEOUT_SECONDS', '300'))
CHAT_AI_ASSISTANT_USERNAME = os.environ.get('CHAT_AI_ASSISTANT_USERNAME', 'ai-assistant')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Windows LAN server sets no SECRET_KEY env var, so it keeps this exact value.
# Cloud deployments must set a real SECRET_KEY env var.
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-^*pvqm&za4c4%6$bnc+0i22xcl)r6oy(p(ar#vxsm80^cc-6_@',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to True (existing LAN-server behavior); cloud deployments set
# DJANGO_DEBUG=False.
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '*').split(',')

# Self-signed HTTPS is served directly by Daphne on 8000 (see DEPLOYMENT.md) so
# that WebRTC's getUserMedia works from LAN clients other than the server box
# itself (browsers require a secure context — https or localhost — for camera/
# mic access). Django enforces Origin-header checking on unsafe HTTP methods,
# so the https origin needs to be explicitly trusted here.
CSRF_TRUSTED_ORIGINS = os.environ.get(
    'CSRF_TRUSTED_ORIGINS',
    'https://192.168.88.30:8000',
).split(',')

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Application definition

INSTALLED_APPS = [
    'daphne',  # must precede staticfiles so Channels' runserver substitution takes effect
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.humanize',
    'django.contrib.staticfiles',
    'channels',
    'rest_framework',
    'core',
    'planning',
    'printing_plates',
    'migration',
    'qc',
    'workflow',
    'manual_working',
    'reports',
    'theme',
    'production',
    'supply_chain',
    'job_summary',
    'audit',
    'tasks',
    'backup',
    'sheets_sync',
    'maintenance',
    'floor_dashboard',
    'chat',
    'bot',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Offset_ERP.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'core/templates',
            BASE_DIR / 'Job_card_html',
            BASE_DIR / 'printing_plates/templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.software_version',
                'core.context_processors.navigation_permissions',
            ],
        },
    },
]

WSGI_APPLICATION = 'Offset_ERP.wsgi.application'
ASGI_APPLICATION = 'Offset_ERP.asgi.application'

# NOTE: the Redis instance already running on this dev machine is v5.0.14, which
# predates the RESP3 HELLO handshake (Redis 6+) that redis-py negotiates by
# default — hence `protocol: 2` (RESP2) below. Drop this once Redis is upgraded.
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [{
                'address': f'{REDIS_URL}/0',
                'protocol': 2,
                'socket_connect_timeout': 5,
                'socket_timeout': 10,
                'retry_on_timeout': True,
            }],
            'capacity': 1500,
            'expiry': 60,
            'channel_capacity': {
                'chat_presence': 200,
            },
        },
    },
}

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': f'{REDIS_URL}/1',
        'OPTIONS': {
            'protocol': 2,
        },
    },
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.CursorPagination',
    'PAGE_SIZE': 30,
}


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# The Windows LAN server sets neither DATABASE_URL nor SQLITE_PATH, so it
# keeps using the exact SQLite config below (db.sqlite3 in the repo root),
# unchanged. Cloud deployments can either:
#   - set DATABASE_URL=postgres://... to use Postgres, or
#   - set SQLITE_PATH to relocate the SQLite file onto a mounted volume
#     (e.g. Docker) while keeping the same WAL-tuned SQLite engine.

if os.environ.get('DATABASE_URL'):
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.parse(os.environ['DATABASE_URL'], conn_max_age=600)
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.environ.get('SQLITE_PATH', BASE_DIR / "db.sqlite3"),
            'OPTIONS': {
                'init_command': (
                    'PRAGMA journal_mode=WAL; '
                    'PRAGMA busy_timeout=5000; '
                    'PRAGMA synchronous=NORMAL; '
                    'PRAGMA temp_store=MEMORY; '
                    'PRAGMA cache_size=-2000;'
                ),
            }
        }
    }

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Karachi'

USE_I18N = True

USE_TZ = True

# Authentication
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
# Only used by `collectstatic` for cloud deployments (Nginx serves from here);
# `runserver`/Daphne on the Windows LAN server serve static files directly
# from each app's static/ dir regardless of this setting, so it's a no-op there.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# ERP software version information
ERP_SOFTWARE_VERSION = '2026.07.03.1'
ERP_SOFTWARE_RELEASE_DATE = '2026-07-03'

# Optional label identifying which server instance created a backup (e.g.
# "CloudVM", "Production"). Blank on the Windows LAN server by default so its
# filenames are unchanged; set via env on the cloud deployment to distinguish
# backups when multiple instances sync to the same Drive/OneDrive account.
BACKUP_INSTANCE_LABEL = os.environ.get('BACKUP_INSTANCE_LABEL', '')

# Lock older operational records from edit for non-managerial roles.
ERP_RECORD_EDIT_LOCK_DAYS = 2

# Chat module
CHAT_ICE_SERVERS = [
    {'urls': ['stun:stun.l.google.com:19302']},
    # Future (remote/VPN users): add a TURN entry here, e.g.
    # {'urls': ['turn:lan-turn-server:3478'], 'username': '...', 'credential': '...'}
]
CHAT_MEDIA_SUBDIR = 'chat_media'
CHAT_MAX_ATTACHMENT_MB = 25
CHAT_ATTACHMENT_RETENTION_DAYS = 180
CHAT_MESSAGE_EDIT_WINDOW_MINUTES = 15

