# Generated by Django 6.0.4 on 2026-07-15 18:06

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_enabled', models.BooleanField(default=True, help_text='Enable or disable automated backups.')),
                ('backup_time', models.TimeField(default=datetime.time(20, 5), help_text='Time of day when the backup should run.')),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='DAILY', help_text='How often backups should run.', max_length=10)),
                ('local_backup_folder', models.CharField(default='backups', help_text='Local directory where backups will be stored.', max_length=255)),
                ('cloud_onedrive_folder', models.CharField(blank=True, help_text='Path to OneDrive sync folder (e.g. C:\\Users\\Name\\OneDrive\\ERP_Backups)', max_length=255, null=True)),
                ('cloud_gdrive_folder', models.CharField(blank=True, help_text='Path to Google Drive sync folder (e.g. G:\\My Drive\\ERP_Backups)', max_length=255, null=True)),
                ('keep_daily', models.IntegerField(default=30, help_text='Number of daily backups to retain.')),
                ('keep_weekly', models.IntegerField(default=12, help_text='Number of weekly backups to retain.')),
                ('keep_monthly', models.IntegerField(default=12, help_text='Number of monthly backups to retain.')),
                ('include_media', models.BooleanField(default=False, help_text='Include the media folder inside the backup archive.')),
                ('include_logs', models.BooleanField(default=False, help_text='Include system logs inside the backup archive.')),
                ('enable_notifications', models.BooleanField(default=True, help_text='Enable notifications on backup success/failure.')),
                ('enable_encryption', models.BooleanField(default=False, help_text='Enable ZIP password encryption.')),
                ('encryption_password', models.CharField(blank=True, help_text='ZIP protection password.', max_length=128, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Backup Setting',
                'verbose_name_plural': 'Backup Settings',
            },
        ),
        migrations.CreateModel(
            name='BackupHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_type', models.CharField(choices=[('AUTO', 'Automatic'), ('MANUAL', 'Manual')], default='AUTO', max_length=10)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('finish_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, help_text='Duration of the backup operation in seconds.', null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.BigIntegerField(blank=True, help_text='Size of backup file in bytes.', null=True)),
                ('backup_location', models.TextField(blank=True, help_text='Path(s) where the backup is stored.', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sha256_checksum', models.CharField(blank=True, help_text='SHA-256 hash of the generated backup zip file.', max_length=64, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who initiated manual backup (null for automatic).', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Backup History',
                'verbose_name_plural': 'Backup Histories',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='RestoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='SUCCESS', max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('backup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backup.backuphistory')),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Restore History',
                'verbose_name_plural': 'Restore Histories',
                'ordering': ['-timestamp'],
            },
        ),
    ]
