# Generated by Django 6.0.4 on 2026-08-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupsetting',
            name='media_cloud_folder',
            field=models.CharField(blank=True, help_text="Optional: send media to a DIFFERENT destination than the database backup (local path or rclone remote, e.g. gdrive:ERP_Backups/CloudVM). Only used when 'Include media' is on. Leave blank to bundle media into the same zip as the database, sent to both OneDrive/Google Drive folders above as usual.", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='backupsetting',
            name='cloud_gdrive_folder',
            field=models.CharField(blank=True, help_text='Windows: path to Google Drive sync folder (e.g. G:\\My Drive\\ERP_Backups). Linux/cloud servers with no desktop client: an rclone remote instead, e.g. gdrive:ERP_Backups/CloudVM', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='backupsetting',
            name='cloud_onedrive_folder',
            field=models.CharField(blank=True, help_text='Windows: path to OneDrive sync folder (e.g. C:\\Users\\Name\\OneDrive\\ERP_Backups). Linux/cloud servers with no desktop client: an rclone remote instead, e.g. onedrive:ERP_Backups/CloudVM', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='backupsetting',
            name='include_media',
            field=models.BooleanField(default=False, help_text='Include the media folder in the backup.'),
        ),
    ]
