# Generated by Django 5.2.16 on 2026-09-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0002_backupsetting_media_cloud_folder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backuphistory',
            name='cloud_sync_details',
            field=models.JSONField(blank=True, default=dict, help_text="Per-destination sync result, e.g. {'onedrive': {'link': ..., 'synced_at': iso, 'duration_seconds': n}, 'gdrive': {...}}."),
        ),
        migrations.AddField(
            model_name='backuphistory',
            name='notification_sent',
            field=models.BooleanField(default=False, help_text='Whether the success/failure email for this run was sent.'),
        ),
        migrations.AddField(
            model_name='backupsetting',
            name='notify_email',
            field=models.CharField(blank=True, default='mahmood.hassan@utopia.pk', help_text='Comma-separated address(es) emailed after every backup run (success or failure) when notifications are enabled.', max_length=255),
        ),
    ]
