# Generated by Django 5.2.16 on 2026-09-17 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0003_backuphistory_cloud_sync_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backuphistory',
            name='targets',
            field=models.CharField(default='both', help_text='Which cloud destination(s) this run covered: both/onedrive/gdrive. Set when OneDrive and Google Drive run on separate schedules.', max_length=20),
        ),
        migrations.AddField(
            model_name='backupsetting',
            name='gdrive_backup_time',
            field=models.TimeField(blank=True, help_text="Optional: run the Google Drive sync at its own time, separate from OneDrive. Leave this AND the OneDrive time above blank to back up both together at 'Backup Run Time' above.", null=True),
        ),
        migrations.AddField(
            model_name='backupsetting',
            name='onedrive_backup_time',
            field=models.TimeField(blank=True, help_text="Optional: run the OneDrive sync at its own time, separate from Google Drive. Leave this AND the Google Drive time below blank to back up both together at 'Backup Run Time' above.", null=True),
        ),
        migrations.AlterField(
            model_name='backupsetting',
            name='backup_time',
            field=models.TimeField(default=datetime.time(20, 5), help_text='Time of day when the backup should run. Used for BOTH destinations together, unless the two override times below are set.'),
        ),
    ]
